#+TITLE: The Scent of Plum Blossoms
#+AUTHOR: P. Schreiber


On a moonlit night, even though they aren't seen, isn't it true 
That we can know the plum flowers by following their perfume?
— Ôshikôchi no Mitsune, Kokin Wakashu #40, translated by L. N. Hammer
	
His Highness Sanjonomiya, elder brother of His Majesty, lived in a mansion in the Capital with four wives, but his heart had a place for only one. The first wife never cared for the husband’s affection, and had taken religious vows a long time ago; neither did the third, whose joy in life concerned the care of her daughter and son-in-law. But the second wife had lived a beautiful love story with His Highness, and its end sprung rivers of tears that refused to dry. It was almost ten years since the last time her husband came to visit, and all that remained of that great love was a mild gratitude for the comfort he provided her, and boredom with the cloistered life she led every day.
So it was that one day Ninonyobo, the second wife, visited the nun who lived in the southeast wing of the mansion, accompanied by her trusted handmaiden. The courtyard of the house had a green lawn and a clear pond, with rocks covered by moss; a well-kept garden, with no flowers. The house itself looked comfortable, but no decorations could be seen. It was a fitting abode for someone whose heart was not set on this world, but in that which lies beyond this life.
“Greetings,” said the nun from across the wooden blinds that isolated her chamber. “Tell me, what brings a distinguished lady such as yourself to my humble dwelling?”
It was a long time since Ninonyobo had last left her house in the southwest wing. “I seek the joy which is lost to me,” she said. “A way to end the suffering that has been my fate in these past years. Since His Highness went away, my sleeves have ever been wet with tears.”
“Such is the heart of men, is it not?” said the nun. “Their love is fleeting, ever seeking new adventures, a new bud just after the first blossom has bloomed.”
Ninonyobo’s cheeks paled, her voice faltered, when she realized that this was just the sort of predicament she herself must have put His Highness’s first wife into, when their love began, many a year ago. But that venerable woman’s tone was not hostile; rather, she spoke as one who commiserates with the suffering of others, and mends it with kindness and care. “Do come inside, and tell me about your sorrows,” she said.
Now that she thought about it, Ninonyobo could not recall the last time she saw that lady—or if she had ever seen her at all. She crossed the blinds and stepped into the chamber. It was dark, but she could see the nun, sitting behind a thin white curtain with a rosary in her hands, and scrolls lying on the floor.
“Excuse my impoliteness, but I must know,” asked Ninonyobo. “Do you begrudge me for taking His Highness from you? Alas! It seems so shameful of me to confide my sorrows to you, when I myself wronged you the same way. I hope you will forgive me.”
The nun’s voice had a motherly tone as she answered. “Do not let your heart be disturbed by such unfounded worries. My bond to His Highness is no more than a familial matter, and never has he given his heart to me, or I to him, though I was ever faithful. When you came to him, I had already fulfilled my duties, and it was time he found someone his heart truly desired.”
She stopped talking for a moment, and lifted her eyes from the rosary to look at Ninonyobo. “Ah, now I see why this pains you so much. Such youth, such beauty; what a waste it would be for you to spend this precious life alone, abandoned. You remind me of how I was a long time ago, in a time I had forgotten.”
Ninonyobo noticed the short, shoulder-length hair of the nun, and pitied her for forsaking her womanhood to dedicate her life to endless prayers.
“Oh, pray tell me,” Ninoyobo pleaded. “How did you heal your loneliness, and find peace with no one to live with, to love or to be loved by?”
“Well, I am hardly ever alone; there are many women in this house to bother me and interrupt my prayers,” said the nun, giggling, covering her face with her sleeves; a gesture of courtly modesty that even all those years of ascetic life could not erase. “I will tell you: it is not only with this life that you must concern yourself. If you find that your duties are all done, and your pleasures are over, then you should turn your heart towards the life that is to come, and see to it that you are deserving of a better fate than that which you were given in this one.”
The thought of taking religious vows, forsaking the life she led to dedicate herself to the spiritual world, had never before passed through Ninonyobo’s mind. Could she find the peace she yearned for therein, letting go of her long hair, her fancy robes, and, most of all, human affection?
“It will not be easy in the beginning,” said the nun, her voice now grave and solemn. “You will feel your heart turn cold, and the world will seem devoid of light. You will forget what it is to sleep, and feel tired all the time. Then, in the silence, the loneliness of all the years will swell up and overflow at once, making you cry until your eyes are dry.”
The nun sighed, as if a memory passed through her like a gentle breeze. “But one day, all that will pass, like it never happened. And you will feel a warmth in your heart; peace, at last.”
That was a comforting thought; as for the bad part, the lady already felt that her life was just like that, and could not get worse. Perhaps it was time for her to let go.

#

In the following days, Ninonyobo reflected on the subject, and decided to follow the nun’s advice. She composed a letter to His Highness, which she sent through her handmaiden Chunagon.
The Sanjo mansion was composed of several gardens and buildings. Most important was the north hall, where His Highness lived with his fourth wife and his closest servants. This day, it was open for richly dressed guests, and the sound of music echoed from the interior, though the musicians were hidden behind curtains and blinds. It was a special occasion, and a feast had been arranged to celebrate the visit of His Highness’s nephew, the son of His Majesty’s firstborn, the former Crown Prince, most admired among the royal sons.
The last time His Highness had seen his nephew, he was nothing more than a boy without a care for anything in the world. But his father’s passing changed the young prince, and he strived to be worthy of renown, studying with great scholars, practicing all the arts, and becoming a man of great tastes, even in his young age. And so, he was named Umenomiya, the plum blossom prince, in reference to that well-known poem about flowers that bloom in the dark.
Hearing the beautiful music of flutes and strings, the handmaiden Chunagon awaited on the porch, as a servant of His Highness took the letter from his wife. As she stood there, she wondered who it was that played the strings; “almost as beautifully as my lady,” she thought.
In the main hall, Their Highnesses discussed present affairs and reminisced about the past, when the letter came, crafted in colourful paper, written in elegant calligraphy; not an ordinary note, and it caught both by surprise. His Highness Sanjonomiya started reading silently, wondering why his wife, whose handwriting he recognized at once, would send such an unexpected letter. But as her intent became clear, in anger he could not maintain the silence.
“After all these years, I realise that, just as the seasons pass, so do the feelings in people’s hearts. Now, the warm and joyful days of summer have passed, turned to autumn, when flowers wither and fall. Therefore, before the winter comes, I need to find shelter for my heart. So, I ask you to be good to me once more: release me from this life, and allow me to take vows and dedicate myself to the next.
‘Won’t come back again a love that is departed, like the gods command 
That the flowers when they fall don’t return to their branches.’”
His Highness Umenomiya sat quiet and embarrassed, as his uncle’s face turned red.
“This is a disgrace, a shame!” thundered His Highness. “And it shows you how cruel a woman’s heart can be, even after years of sincere affection. I keep her in my house, provide for her every need, treat her with utmost respect, and what does she repay me with? Disregard and abandonment.”
“Indeed, Your Highness,” nodded the nephew, but his countenance revealed neither agreement nor discordance. “But I am certain it is only in sorrow that she says these things. A lonely woman may—”
“Nonsense! She has no reason to feel sorrow; it is I who suffers a great injury.” He took time to breathe. The music had stopped, and their voices sounded inside and outside the hall. “It does not matter, it is clear to me that she does not say this out of spiritual devotion, but rather a desire to hurt me. Therefore, I have no reason to agree to this foolish decision, only for her to regret it afterwards.”
His Highness Umenomiya cleared his throat. “So, are you going to write to her now? I will leave you to it in private, and we may continue our conversation on another occasion.”
The uncle shook his hand, signaling it was nothing, and they left the matter aside. From the veranda, Chunagon heard everything, and wept for her lady. That afternoon, she went back with no reply.

#

It was late in the afternoon when His Highness Umenomiya excused himself from the company of his uncle and left the mansion. The sky was dark, as were the leaves and the surface of the waters of the garden. The young prince was tired of the conversation, and longed for a lighter company; a fun pastime to relieve him of worldly worries, and not more worries to add to his own.
As his ox cart made for the gates of the mansion, he heard the faint sound of koto strings. It was a slow, sad melody; of someone who plays as she cries, hitting each note as if it were a thought, a feeling, a memory. He was moved by it, and could not hold back the curiosity. He reckoned the music did not come from the main hall; that building was far, and this player was more skillful than either the lord or the lady of that house.
He stepped from the cart and followed the sound, searching its source. It led him across a bamboo thicket in the southwest section of the mansion, from where he saw the roof of a building. Its windows were still open to the cold air of the early spring, but the blinds were down, and not much of the interior could be seen.
In the silent hour of dusk, even from the outside he could hear the wood resounding under the strings. As he approached, the air carried to him the voice of a woman, softly singing the notes she played on the koto, with the slightest vibrato. He realised that the player was perhaps the lady who wrote that letter; lovelorn and sad, having received no reply from her husband, much less a loving one. He, who also felt a yearning in his heart, was charmed by her voice, and sympathized with the feelings it conveyed. Without thinking, he found himself humming the same tune.
Inside the house, the music stopped; blinds and curtains rustled, and shutters slammed. His little promenade had made more noise than he intended. Before trouble found him, the adventurer left the mansion, as the veil of night covered the Capital of Peace and Tranquility.

#

A cold mist hung in the air, in the early hours of the morning. Ever since she decided to speak to His Highness again, and he never replied, Ninonyobo felt more sorrow than ever, so that when she woke up, it was as if she had slept outside in the dew, so damp were her sleeves with tears. She spent her days reading collections of poems, finding comfort in the verses about the seasons, love, and loneliness. They made her feel that she was not alone in her suffering. However, she never had the motivation to compose any poetry of her own, asking, “what use is a poem that is left stored in a drawer, forever unread?”.
Chunagon rushed across the boards, her steps disturbing the silence of the house. She hurriedly entered the chamber, clutching her chest with two hands. The lady took her eyes off the page she was reading, and looked at the handmaiden; first with annoyance, then with curiosity. Her face was flustered, red, and her forehead was wet with sweat, as if she had run or, what was stranger in that place where nothing happened, as if she were nervous. She sat on a cushion and slid her hands, covered by long sleeves, under the standing curtain, leaving there a letter.
After weeks, Ninonyobo lost all hope that her husband would answer her message. Now, she could not believe what her eyes saw. It was a beautiful scroll, wrapped in purple paper and tied with an elaborate knot, shaped like a flower. When she removed the purple wrapping, a strong scent of floral incense invaded her senses. The craftsmanship behind the letter puzzled her. Not that His Highness was not a man of refined tastes; but it was strange that he would do this now, after all this time, especially considering the contents of her letter.
Without a word, she unrolled the letter. Surprise turned into horror. She reached for one of her lacquered boxes, and opened one of the old letters from His Highness. To her dismay, the handwriting on the two was quite different—not in the way time changes one’s letters, but in the way that distinguishes the hand of one man from that of another. And it was indeed the handwriting of a man; each character distinct, like the letters of someone used to writing official documents, texts designed for easy reading, not private letters and calligraphic practice of poetry. Yet, it was not without charm. Just as the writing of a woman, the characters flowed with flair and grace, flourishes and twists, the brush never leaving the paper.
Ninonyobo covered her mouth with her sleeves, lest she reveal that she gasped at the contents of the letter. She lifted her head and looked at Chunagon; from the other side of the standing curtain, the handmaiden’s face revealed a mischievous smile. Such was the weight of the lady’s emotions, that she could not keep silent, and whispered the words of the letter.
“Ever since I learned about your existence, I sought you; for I knew that a treasure such as your heart cannot be made to suffer loneliness and hardship. That is a crime greater than any other. I have heard the music that is kept inside the walls and curtains of that house, hidden; now I am forlorn too, for the melody has touched my soul, and I cannot be at peace. 
‘Koto strings that night, a bond that can’t be severed, tied my heart to yours
The music leaves me wand’ring until I hear it again.’”
As she finished reading the letter, Ninonyobo sighed, breathed, then read it again, to make sure she was not imagining things. She thought she would swoon. The other night, she had seen the intruder who crossed the bamboo thickets to hear her play, alerted of his presence by Chunagon; the same Chunagon who now tried to throw her life in disarray. Looking at the handmaiden, she searched for questions she could not—or dared not to—voice.
“How did you come by this letter?” was the only thing she could manage to ask, as quietly as possible. They were not alone in the house, and bamboo blinds made for terrible keepers of secrets. 
Chunagon made the best effort to restrain her excitement and keep her voice low. 
“I was at the garden when a page boy came and called me to the gates, where a stranger awaited. Outside, there was the large cart of a nobleman, heading to the Imperial Palace. As I approached, the side shutters opened, and a man said, ‘I have a message for the lady of the southwest wing, and I trust you can deliver it to her hands.’ Though his face was hidden, I thought the voice was familiar. 
“I was nervous, but I told him, ‘well, it is inappropriate to send words to a lady such as the one who lives in this house, especially in secret.’ And this is what he said, “I am someone who heard the music that your lady plays; who knows her heart, and what fate has brought her to. And I hope that, by this message, the watcher will not keep me from hearing it again.”
The handmaiden stuttered. She was embarrassed, and let slip a secret she was keeping for weeks. “In the northern house, I heard His Highness say he would never give my lady leave to take religious vows. I am sorry, I could not find the strength to tell you, and left you waiting for a reply that would never come. When this letter came, I thought it would relieve my lady’s sorrows.”
As she heard the explanation, Ninonyobo searched her stuff for inkstone, brush and paper. Chunagon smiled, excited; but the lady glared at her with a serious face.
“This is unacceptable,” she said. “Yes, I may be in a bad state now; and oh, how sad it will be if His Highness will not allow me to take vows like the lady of the southeast wing. But this is absurd, and if word gets out, I will be thrown in disgrace, which is a worse fate.”
She took up the brush, dipped it in the black ink, and put it on the paper. After hesitating for a second, she pulled up her spirits and wrote. She handed the reply to Chunagon, who read and smiled, noticing that her lady’s handwriting was the most elegant and charming, even in these words of refusal:
“‘To this wretched house, forgotten by time and love, the strings don’t bind you.
To someone else we are both bound by fate, not by our wills.’
To break these strings that bind us would be a sin.”

#

The chilling breeze of the night blew through a breach in the shutters, bringing in the perfume of plum flowers in full bloom. Ninonyobo woke up restless, feeling her robes wet and hot—this time, not with dew, nor tears. She had dreamed the most unbecoming of dreams.
The scent from the garden brought to her mind the thought of someone she ought to have already forgotten. Unable to control her heart, she woke up Chunagon, and asked her to close the shutter that was left open.

#

The passing of days and weeks was not enough to erase the lasting impression that the plum flowers had made on the lady of the southwest wing of the Sanjo mansion. Ever since that dream, Ninonyobo was in high spirits; a joy to herself and to all the gentlewomen of the house, though most were oblivious to what had caused such a change in her heart—either by ignorance, or by discretion.
One day, Chunagon was called to receive the visit of an old gentlewoman named Taifu, bearing a message from His Highness Sanjonomiya. Such a long time had passed since she had gone to the north hall to deliver her lady’s message, that she never thought that a reply would actually come. But it did; and what was her surprise when she saw that the gentlewoman was accompanied by two pages, bearing boxes of gifts.
Chunagon ordered the boxes to be carried to the main chambers, as she grabbed the letter and handed it to her lady, who read it in a soft but clear voice.
“It was a great sorrow to learn about your desire to forsake our life together, without any consideration for the memories we built and the moments we lived; a thought that inflicts a painful, deep wound in my heart, which has ever been faithful and devoted to you with earnest affection. Still, without forcing my own wishes upon you, I decided to give you time to think, in hopes it would give you the clarity to let go of this foolish idea of taking religious vows.”
The lady stopped reading for a moment, and played with a lock of hair. She almost forgot she had had the idea of cutting it short, to live as a nun. With a smile on her face, she continued reading.
“To prove my affection to you is as strong as ever, I send you these gifts of silk, with the certainty that you will be able to turn the fabrics into things of great beauty.”
Ninonyobo covered her mouth with her fan, unable to hold back a laugh. “Ah, yes; robes which I am sure will serve to increase the beauty of his lady of the north hall,” she gossiped with Chunagon.
There was not even a poem in the letter, and not much more that the lady was inclined to read. They searched the contents of the boxes. There were thin silks in pink, white, green, and other colours. A wonderful gift, indeed, that they wondered if the lady would ever enjoy.
“It seems His Highness still holds my lady in high regard,” Chunagon tried saying, without much enthusiasm.
The letter was polite and kind enough. Nevertheless, it did not surprise them that His Highness did not come to visit that night, or in any of the nights that followed. The ink on the paper was as much of a display of affection as Ninonyobo would receive.

#

As the spring gave way to summer, the days got so warm that it became impossible to keep any shutters closed, and the women of the house felt their arms tired of waving their fans. To pass the time, Ninonyobo tried to write some poetry, but there was not much inspiration inside the house, and even as she put her brush on the paper, the ink flowing in that hot weather made her feel as if she herself would melt and vanish. And so, Chunagon introduced her lady to tales. In the past, Ninonyobo had thought them to be vain and foolish; but that was until she was caught between the pages of a compelling love story. Now, she took great pleasure in reading them, finding herself mirrored in the characters, and taking on the adventures she was not allowed in her real life.
One afternoon, Ninonyobo had the blinds rolled up, so that she could enjoy the sight of the garden, beautiful under the clear blue sky. Chunagon, who had been absent in the morning, now came back to the house; and, when their eyes met, she revealed a scroll of coloured papers, hidden inside her robes. The lady was distressed, and looked at the other women in the house. Among them was Taifu, her husband’s servant, who had many years of service, a keen eye for suspicious behaviour, and these days was being unusually close and solicitous to her master’s wife.
In the kindest voice and countenance she could produce, the lady of the house turned to Taifu, and asked if she could fetch her koto. “Writing is beyond my strength now, and my mind cannot bear this cruel weather. Perhaps some music will help us pass the time; a joyful summer tune to raise our spirits, or a wintry tune to take our hearts away from the heat of this season.”
The old woman suffered as much as anyone in that heat, and the thought of relief was more than enough to make her stand up to bring the instrument to Ninonyobo, without suspicion. After all, what was there to suspect in such a request? Just as she left the room, Chunagon rushed from the garden to the veranda, reached into her robes, and delivered the letter to her lady. 
Instead of words, what they discovered in the scroll was that, as the lady unrolled the colourful, perfumed paper, a shower of petals fell on her lap; petals of the white and silky plum blossom, fresh as if they had been gathered on that very day. 
“In the dark of night, just as the plum blossoms fall, I will come to you.
Lead me in with a song to end my longing for your heart.”
Ninonyobo whispered the words of a poem she remembered from a dream, and not from the real world.
“Well, if the papers are blank,” Chunagon dared to say, “I guess that can only mean that it is meant for you to write a reply to His Highness.”
“Hush! what are you saying?” with a grave face, Ninonyobo chided the woman, who seemed obstinate to cause trouble and forget her proper place.
They heard steps on the boards, and heavy breathing; Taifu, carrying the heavy instrument with her own hands. They stopped the gossip, hid the papers, and threw the petals in the air.
“Oh, spring showers,” said the innocent old Taifu. “How beautiful the white blossoms look.”
Chunagon smiled, “Yes, it is going to be a lovely season indeed.”

#

His Highness Umenomiya was again visiting the Sanjo mansion. Their Highnesses made music together, and Chunagon, who listened in another part of the house, was pleased to learn that the young prince was a good flutist, and able to accompany the strings of the more experienced uncle. But as the uncle’s music was technical, a mere exercise in socialisation, the nephew’s was passionate, intense. Though his body was present at the hall of Sanjo, Chunagon wondered where his heart was, as he played.
Their Highnesses played a merry song, titled Birds on the Orange Twig. Here, beyond the blinds, the gentlewomen of the house gossipped and laughed, each of them longing to be one of the two birds perched on the boughs of that fragrant tree. Chunagon hid her face behind her fan, and smiled.
When the song ended, His Highness Umenomiya started to play a slow tune. The sound of his flute rose above all the sounds around them, resonating and echoing in the wide wooden hall with a melancholic vibrato that conveyed such intensity of emotion, that the women behind the blinds, and in fact every living being that witnessed it, thought it was like the song of the nightingale when there is no sun, and wondered why it was that the handsome prince felt such sorrow. Chunagon remembered the letter she had delivered to His Highness earlier, and the poem written by her lady on colourful papers. 
“Indeed it is strong, the perfume of plum blossoms in the dark of night. 
Yet, the vernal breeze can’t breach through these unopened windows.”

#

There was a refreshing breeze in the air. Chunagon crossed the blinds into her lady’s chamber, and found her behind a folding screen, contemplating her own image. She came closer and combed the lady’s hair, so long that it reached her ankles, even as she stood up; black as the waters of Lake Biwa in the darkest night, without a single white strand. Dressed in two layers of thin silk, white over bright crimson, she looked clothed in petals of cherry blossoms in full bloom, and Chunagon wondered if there was any lady that could equal her beauty, either in this realm or across the sea.
“Do you recognize these silks?” asked Ninonyobo to the handmaiden. “I wonder if these youthful colours are fitting to a woman of my age.”
They laughed, as Chunagon realized they were the fabrics sent by His Highness her husband, some weeks ago.
It was a delicious night. The waxing moon shone in the sky, its glow reflected on the waters of the garden of the southwest wing. The white plum blossoms were like little stars. Such nights touch the heart with love and yearning, and from those feelings Ninonyobo found consolation in music, as she plucked the strings of the koto, accompanying the singing voices of the cicadas.
As the night advanced, one by one the women of the house excused themselves and lay to sleep. Ninonyobo ordered that the windows be shut, explaining that, even though it was summer, the night was windy, and the season was turning. Only Chunagon knew it was not the wind that the lady wanted to keep out, and lowered her head, without saying a word.
Ninonyobo looked at Chunagon, and with a smile hidden behind her sleeves, said, “well, perhaps you could leave one window open; a breach to allow the perfume of the blossoms to come in.”

THE END
