#+TITLE: (Un)Awareness
#+AUTHOR: P. Schreiber

* I

A night time mission. The first one. She definitely did not feel prepared for that. Nako was only a junior at the Animal Crime Department of the Zurich police. A kid, in the eyes of her fellow officers, even in this most peaceful department. Until that day, all she ever heard between the four white walls, plastered with joyful posters of animals running in sunny fields, were the sounds of laptop keyboards and the slurping and bubbling of the coffee machine. But now, the office was agitated; there were loud steps back and forth, locker doors banging, locking and loading. Scary. She heard one of the colleagues say to her, "Here, kid." And there 
was a gun on her table. A stun gun, yes, but a gun nonetheless. This was Switzerland, for God's sake, what the hell.
The patrol car sped through the narrow streets and into the road, sirens wailing. The inside of Nako’s navy nylon jacket felt weird, as she carried the gun for the first time. She hid her hands between her thighs and gazed at her knees, trying to be invisible. Other than her, two of the boys laughed and talked loudly, actually excited about the assignment. How could they be so calm, she asked herself angrily. In the front passenger seat, the Chief brushed with his fingers his thick orange moustache, displaying nothing of the excitement of the youth.
As they reached a factory-like complex, through the windows she saw the lighted letters of a sign, standing on the front lawn. "MOGLE Biolabs," Nako whispered. The Chief cleared his throat--a reflex? "What is it?" she asked.
"Well, kid, I don't know if you've had the time to read the entire manual, but synthozooids actually fall under the jurisdiction of the Animal Crime Department. Well, this is where they are grown."
That made sense, she reckoned. Artificial or not, syzoos were, by all biological standards, animals. According to the briefing, it was reported that two people in black hoodies were riding bicycles close to the lab, then suddenly disappeared from the road. Troublemakers, they suspected. The headlights illuminated the gates of the facility: ajar, with a broken padlock and chain on the ground. "The bastards! Get in there," said the Chief. He turned his head to the back seat and stared at Nako with a grave face. "This is going to be a lot more common from now on, you hear, Kawakami. Damned terrorists."
Terrorists. The word caused Nako to gasp, and she covered her mouth with her two hands. The engine roared, the tires screeched, and the front bumper crashed at the metal gates with a bang that rattled the inside of the car and echoed loudly in the silence of the night.
The headlights revealed a black van, stationed in front of a building shaped like an arched vault. Two figures in black hoodies stood by the open back doors of the van. "Whatever, man! Just run with it," Nako heard the shout of a girl, as the driver stopped the patrol car.
From the building, three hooded figures appeared, sliding a cart. On the cart stood a strange, amorphous creature; or rather, it made its best to stand, for its feet were too tiny for its bulk, and it appeared to have no bone structure. Its furless skin reflected the headlights, white as a paper sheet. In one side, it had what looked like the sketch of a face, with only those basics lines that form the faces of every mammal, like the primal traces of some ancient relative. Two eyelids were shut, hiding unformed, atrophied globes. "Forget the goddamn blanket, Obi. We have to leave now!"
"We got you this time, Obi." The Chief said as he and the rest got out of the car, and put his hands on the belt like a cowboy from an old movie. "Leave that poor animal where it is. We will not allow you to continue to make it suffer."
The hooded figures were hurriedly trying to load the blob creature into the back of the van. One of them came forward to face the Chief. The black hood hid his features in shadow, but Nako saw that his skin was white as snow, and the hair he could not keep inside was corn-yellow. His voice was youthful and vigorous. "You can drop the act, Chief. I don't know if those goons believe your lies, or if they are just as baleful as you. But I know you are full of shit, and you don't even think this creature is able to suffer. After all, that is your whole point, is it not? To create 'an animal that does not suffer'."
"Be that as it may, you are trespassing private property, and disturbing the public order, which is against the law. I am not here to discuss philosophy with you, Obi," said the Chief, to which hooded man laughed. "I am here to arrest you."
"Geez, Chief. Just when I thought we could settle this peacefully." The hooded man clicked his tongue and kicked the lawn. There was a crash of broken glass, as the hooded girl threw a rock at a lamp, startling everyone. Obi ran, stumbled stupidly, and got in the van. "Dash!"
The van roared as the rest entered through the back door with the creature inside. The driver spinned the car 90 degrees, lifting up dust, and dashed towards the gates of the facility.
"What the hell is he trying to do this time?" The Chief asked himself out loud as he entered the car and ordered, "go, boy, chase!" The car was hard to maneuver, but soon it was on the road, chasing the black van. They were at high speed, sirens wailing. Nako felt her throat close, and swallowed hard. 
The patrol car was inches behind the black van. Suddenly, the back doors flung open. In the hurry, they had not shut it properly. Inside the van, the white creature’s whole body swelled like a cake in the oven.
"Oh, shit," were the words of the driver. Suddenly, the creature's mouth gaped with the diameter of a melon, revealing a bright red interior. Its body shook, electrified, and even in the interior of the car they heard a terrible shriek, like a being's first cry of unbearable pain. Then, there was a jet of dark red blood that sprayed like a hose at the windshield.
The driver put the brake pedal to the metal, with an impact that would have launched the four out, if not for the seatbelts. The wipers at full speed could not remove the red stains. There was dead silence for a minute in the car, stopped in the middle of the road. Nako felt her hands tremble, and her body shiver with cold, even in her nylon jacket. "What in the earth, or in hell, was that?" she asked in a stuttering voice, but the Chief only grumbled behind his thick moustache. Through the stained windshield, she saw the night sky painted dark red, and could not clear from her mind that colour, even if she closed her eyes.

* II

The pink-coloured foam spiraled like a drain. Yet, even the sweet taste of strawberry almond latte could not drain and cleanse the anxiety from Nako's head. The floral patterns on the walls and the rococo-style china that seemed always so cute and uplifting to her, now seemed almost unreal, otherworldly. Reality had taken a dark turn to her these last couple of days.
"Hey, are you even listening?" asked the friend Justine in her chirpy voice, shaking her hair. Nako's eyes were blank as she stared at the cup; it was clear she was not listening. "Well, it doesn't matter; my job is boring, I know. By the way, you never told me what it is that you do in the police. ‘Animal crime’, that sounds funny, like cats and dogs wreaking havoc around the city. But didn't animal-related crimes disappear after they started producing syzoo meat?"
"Huh? Ah, yea...kinda,” said Nako, waking up from trance. “Most of the work is pretty harmless, like knocking on the door of someone lighting fireworks and disturbing the neighbour's dog. Guess I was never fit to be a hero like my dad."
The piano jazz in the background cast a melancholic tint on her words. The waiter came to their table with a hardcover notepad in his hands. "I'll have the steak tartare, please," said Justine, excited and hungry.
A sudden rush of acid ran upwards, inside Nako's throat, and she held her mouth not to throw up. "Ugh, I can't believe you are ordering that." The dark red colour filled the background of her mind as she pictured her friend’s dish. In her head, she heard the cry she could not unhear. 
Justine made a face of surprise. “Why not? I’m starving, and I heard it’s fabulous. You should have one too; I thought you liked tartare.”
Nako’s eyes wandered off again, but Justine didn’t notice, and just continued to talk.
“By the way, this has to do with what we were talking before. Isn’t it incredible that we are able to have meat, and at the same time end cruelty, with syzoos? Technology, huh. This makes the years of the meat prohibition feel like such a drag.”
“I suppose,” Nako sighed, and said, averting her eyes, “Listen, I have to go now. I have to do...something.”
“Oh--” Justine said. “You take care, okay? You’re being weird.” They were silent for a moment. But then, Justine approached her face, and with two fingers asked Nako to come close, and whispered. “Hey, don’t freak out, but I think there is a guy staring at us, and not in a good way, you know?
Young or not, naive or not, Nako was a police officer; she knew how to keep calm. She looked around at the people at the cafe. With the corner of her eyes she caught a young man looking at her, then quickly averting his gaze, like a scared rabbit. If spying was his business, he was not very good at it. But there was something about that gaze. As a Japanese descendant in Switzerland, her whole life she had been a stranger, and she knew everything about being stared at. This guy’s gaze, and his curiosity, was not flirtatious, nor had it anything to do with her background. What, then?
“Gotta go,” Nako said, and rushed out as she felt the adrenaline in her veins. On her way out, she realized why she was scared. It was the colour of his skin, white as snow, white as the creature that disturbed her mind. That, and the colour of his hair. He was familiar. She walked on as fast a pace as her five feet would allow. 
“Kawakami,” she heard behind her the youthful voice from the other day. “You’re Kawakami, right?”
Nako turned, despite her body telling her not to. The guy behind her looked like a light pole, some six feet three. Yet, his face was so silly that he could not frighten a child, or even a cat. Under the sunlight, his hair was almost as light as his skin colour. He wore a rock band t-shirt, black turned grey, too large for his thin body, plain jeans, and thick-framed glasses on his face. 
“Sorry, I did not mean to scare you, back at the cafe.” He said, forcing a smile that seemed a little uncomfortable. He had a strong accent, but she could not figure out its origin. “I didn’t want to disturb you and your friend.”
Nako raised an eyebrow, puzzled by his weird demeanor. “You kinda did,” she wanted to reply, but remained silent. The young man failed to take the cue for a couple of seconds.
“I’m Obi.”
She took a step back. Though it wasn’t a complete surprise, she didn’t expect the terrorist who looked so threatening the other day to be this silly-looking boy.
“I knew it!” she exclaimed, turning a few heads on the street. Anger took place of the fear, and she whispered at him, “You’re the terrorist! What do you want with me? Wait, more importantly, how do you know me?”
Obi scratched his greasy, thin hair, and forced out a laugh. “You’re Nako Kawakami, the new girl at the Animal Crime Department. I am no terrorist; we are on the same team, the animal protection team. With that weird name, it was not hard to find out who you are.”
Nako was appalled by the audacity, and offended. “We are absolutely not on the same team!” She exclaimed. Obi covered his ears, which made her even angrier. “I was there at the lab, and I saw what you did: you killed that animal.”
“Exactly,” he replied. “You were there. We wreaked some havoc at MOGLE, didn’t we? I can’t even calculate how much money they lost on that. But that was just the start. That’s why I am here. I want to show you what the ACD does not want you to know.” There was a moment of silence. “Funny you should say I killed it. Yes, it pains me to say I do share the blame for the death of the synthozooid. I miscalculated the response time of the ACD. Yet, let me ask you this: otherwise, what would have been its fate?”
Nako calmed down. She did not expect him to be non-confrontational, and it disarmed her. She stared through the thick frames of his glasses, into his light blue irids. He did not seem boyish at all, now. The silence loomed between them, and she could not bring herself to answer his question. “I don’t want anything to do with you. You are acting against the law, and my duty is to protect the law. Go away,” she finally said, but her voice lacked the resolve to support the strong words.
“All I want is your email,” he said calmly. “To show you the work that we do. I know you disagree with what we were trying the other day, but I want to show you the rest of our work. I don’t want any more problems with the ACD; and especially, I don’t want that to happen again.”
The last words got to her. She remembered, and wanted to cry. She ripped a scrap of paper from a notepad and wrote down her email address. 
“Old-fashioned!” Obi said, teasing. “I like it.”
“God, you are so stupid!” She railed at him, pushing the paper against his hand and dashing off.

* III

There was a climate of great stress at the Animal Crime Department those days. There was gossip in the corridors, and sidelong glances everywhere. Such state of affairs heightened Nako’s awareness, like the instincts of a cat. In the course of weeks, she noticed three unusual things happening at the ACD. 
First, she started to listen carefully to the water cooler talks. From what she gathered, virtually the whole staff had been charged with tasks that involved the monitoring and investigation of the activist group that raided MOGLE Biolabs. More than once she heard the codename “the Swede” being mentioned, with the greatest contempt. It did not take long for her to realize who that was. 
But not everyone was involved. That is, the second thing she realized was that she was left out of the investigation, and only the most innocuous, almost childish tasks were being appointed to her. This would not be so strange, considering she was a junior; however, prior to the events at the lab, the Chief had put hope and trust in her, recognizing her smarts. That disappeared from one day to the next.
Third, she felt watched. The Chief, who was a serious man, but had always been kind and supportive to her, was now silent and inquisitive. He was in her desk two or three times a day, pretending it was nothing, and ever watchful of her computer screen. It was as if there was something to hide; something she could not yet recognize, or was not ready to admit.
It was in one of those occasions that things got sour. Nako was not being an inactive spectator of these strange events; rather, she too had something to hide. She was exchanging emails with Obi. He was not so weird in the internet as he was in real life, she found out. He was friendly, and they chatted about all sorts of things--about how he came from the North and had lived in several countries in Central Europe, working as a computer programmer, and about their experiences as an immigrant and as a daughter of an immigrant. In those emails, he explained to her the history of the group, and another side of history of the so-called post-cruelty world. She read all the material voraciously, and researched through websites and forums, whenever she could escape the watchful eyes of the colleagues.
One day, she heard the deep voice of the Chief behind her.
“You are a smart girl, are you not, Kawakami?” She jumped on her chair. On her screen, there was a decade-old article about a group named Animal Liberation Front, with many photographs. She did not try to hide it, but her eyes widened as she turned her chair, frightened. “I commend you for your efforts to participate in the important investigation we are conducting. But I must tell you, this is an affair that far outranks your station. I...erm, vehemently suggest you stop what you are doing and go back to the tasks to which you were assigned.”
Nako was dead silent.
The Chief smiled at her. “You see, this department works like a clock, and each one is an important cog in the machine. If we don’t do the job we must correctly, the machine breaks. Tell me, can I count on you to do your job? Remember, it’s not for me, it’s for the people, and the animals.”
Nako nodded. When the Chief had finished what he had to say and turned away, she could not hold her tongue, and dared to question. “Excuse me, Chief, but there is something I must ask. Why can’t we cooperate with the activists? According to the material I am reading, their main goal is to end cruelty towards animals. And isn’t promoting animal welfare our mission, too?”
The Chief turned back to her, and for a brief moment she thought he would cause a storm to fall. But he still held a smile on his face as he answered. “Is that what you think? That certainly is what they want you to think, but let me be very frank, and tell you the true objective of this terrorist group: to extinguish the synthozooids and reinstate meat prohibition. You may be too young to remember this, but it was hell back then. Animal crime was rampant, people kidnapped animals from the fields, bred, raised and killed them in ill equipped spaces. All the progress achieved since the Day of Animal Reckoning was on the verge of going to waste. Our mission is to protect animals, Kawakami. Theirs is to bring that hell back. And that is why we cannot cooperate.”
He stopped for a second. “You said this terrorist group wishes to end animal cruelty. There is one flaw in that: it has already been effectively ended. The synthozooid is a scientific achievement that must not be understated. It is a meat producing organism that cannot be harmed, that feels no pain, no suffering. That is a cruelty free world fully realized, and that is why it must be protected from those who seek to destroy it. Does that clarify your doubts, Kawakami?”
She pondered for a second. “Yes, sir.”

* IV

The thoughts of insubordination were cleared from Nako’s head after the talk with the Chief. Still, an unshakable feeling remained in the back of her mind, like an ever-present red sign. There was the strange situation at the office, whose root cause was never clarified. There was the strange incident at the lab, which left her nauseated even now. These things interconnected with each other in a myriad of conjectures, leaving her with the ever-growing thirst for the answer to one simple question: “who is lying?”
It did not take long for truth to come out. It was half past noon at the office, in the middle of lunch breaks, when one of the officers charged with surveillance stood up from his chair and spoke, “Sir, there is something wrong with the cameras in sector I-15.” The Chief approached to take a look. It was a residential area, with nothing special to worry about; probably some malfunction in an old equipment. But then, other voices sounded. Sector I, H, G, and all others went out, one by one. The cameras stopped responding to movement; then, all screens went grey.
Nako was sitting on her chair, eating fruit salad and writing a report. As she pressed the “send” button of the email, a message flashed on her screen. “Can’t send now. Try again later.” She looked around the office, and saw that everyone looked dumbfounded. Yet the computers were still connected to the internet. It was outbound communication that was severed.
Nako puffed, annoyed by the situation. Today was the deadline for the report, and she didn’t want to get in any more trouble with the Chief. “Well, it ain’t my fault,” she said to herself, as she forked a green seedless grape. But then, she froze, staring at the screen, at the white contours of the unresponsive inbox. A chill went up her spine, pushing a frightening idea to her mind: maybe it was.
Nako locked the computer and rushed out, avoiding eye contact with everyone. Past the elevator, she took the stairs. As she rushed down, the knock-knock-knock of her shoes echoing with every step, she took ter cell phone from her pocket, and prayed that mobile data was still working in that building.
“Justine,” she sent. 
“Justine.”
“Justine, answer please!”
As she waited, she searched her personal inbox for the emails she had exchanged with Obi. Aside from the links to pages of strange domains, all emails contained attachments, even if the files were unrelated to the conversation. The cellphone bleeped.
“Hey, what’s going on?” Justine asked.
“I need to ask you something. Remember that computer nerd guy you used to date? I need to talk to him.”
“Really, you want me to owe that asshole a favour?”
“Please.”
She could almost hear the annoyance on Justine’s words. But the number came, and she called the guy. It took three attempts before he would pick up the phone, surprised by the identity of the caller. She told him what happened—save the details that could put either of them in big trouble—and, though he would not open the files, he agreed to take a look at some screenshots.
Back at the ACD, the situation had worsened. All computers were shut down to avoid data corruption and theft. People were off their desks, and the temperaments were so hot that no amount of air conditioning was enough to relieve the anxiety. The talk in the corridors was that it would take at least twenty-four hours to solve the problem. Nako stood by the door of the office, unable to enter, unable to face the crowd. She pressed her back against the white wall, wishing it would swallow her, make her disappear.
Eyes closed, she felt a tremor in her body. Her cell phone bleeped again, with a message from her friend’s ex. “Hey, I looked at your screenshots. There really is something odd about this. If this guy just wanted to send you some papers, he wouldn’t have sent all this other stuff. And about these links, well, it could be that he used the content as bait to keep you connected to the pages, meanwhile cracking through your firewall and infecting your network. He would have to be a ninja, but it can be done.”
Twenty-four hours; if it really was Obi who put down the ACD network, it would not have been for nothing. Silly though he were, he did not look like someone for useless pranks. This was a calculated action, and it was her fault. On these things Nako pondered, as she walked to her locker. She covered the stun gun in the blue nylon jacket, and hid it in her bag. Now, it was on her to counteract.
When the sun set, Nako turned the key and started the engine. Hers was a pocket-size two-seat electric car, not at all like the powerful patrol car at the police station. But it would have to do. She drove as fast as she could to the only place she could think where she could find Obi: MOGLE Biolabs. 

* V
She found him in darkness of the lab, the tapping of keys echoing under the murky canopy, and only the faint light of code letters on the black screen illuminating his pale face, hidden under the hoodie. As her steps indicated her approached, he stopped typing. “Hey, Nako. I was wondering if you would show up,” he broke the silence.
“Stop whatever you are doing, Obi,” she said. In her hand, she held a communication device, with a direct channel to the ADC central; in her other hand, the stun gun, pointed right at him.
Obi put his hands off the keyboard. As her eyes got used to the murk, Nako distinguished that he stood by the stack of hardware of a mainframe. He put his hands to his head, as he stepped aside.
“Seven years ago, we were faced by a horrible reality,” he started. “Yet instead of working to end cruelty, we decided to design a being unable to feel our cruelty. How horrifying is that, the fact that we were unable to overcome our bestiality? Despite the whiteness of the walls of this lab, and the technology of our tools, and the complexity of our calculations, this is the root of all: bestiality, and disregard for pain and suffering. Let me show you the true nature of bioengineering, and their so-called post-cruelty world, Nako.
Click, click. The sound of switches flicking echoed across the lab. White lights revealed a corridor with tall glass windows to the left and to the right. Obi walked across, taking light steps, almost solemn; it was as if he walked the corridor of a cathedral. Nako lowered the gun, but followed him with her finger on the alarm. As she approached, she saw two cubicles behind the first and second windows, so white in all their sides that it hurt the eyes. But before she reached the third, she stopped, and could not back a gasp of horror.
On the window of the third chamber, a dark stain of blood splashed and ran down like the waterfall of river Styx.
“Oh, no!” Nako exclaimed. With trembling hands, she raised the gun and pointed at Obi. It was futile; she couldn’t aim even if he were one feet close. “Did--did you do this?” she asked him. Looking further ahead, she saw that the white walls of the other cubicles were painted red.
“Maintenance cleaning,” said Obi criptically. “You must be wondering why there is nothing in the first chambers.”
“No, I hadn’t come to that, yet.” She answered with anger in her voice. “Obi, did you do this? Did you come here to kill synthozooids?”
“No, of course not,” he said. “This is just routine procedure. You see, this is not a farm, but a research facility. And in order for progress to be achieved, there must be sacrifice. This is what they believe. It is just as it was with the ancients, that blood of the innocent be spilled for the growth of the crops or the amusement of the crowd. It is not news, by the way. Every medical achievement in modern human history is supported by columns made of bones from millions of dead rodents. But now, they have the audacity and the cynicism to claim to have ended cruelty. Tell me something, does this look compassionate to you?”
Obi walked towards her, and put his hand on his pocket.
“Stop!” Nako shouted at him, and put her finger on the trigger. “I don’t wanna hear your bullshit. You pretended to be a friend, and used me to get here. I don’t care about your plan, your cause, your nothing. You are a lawbreaker, and a--”
“Terrorist?” he asked. He raised his hands and put them on his head. From his finger dangled a card, chained to a keyholder.
“Liar--” she said, and Obi smiled. “But I can’t let you do whatever you will. I have a duty, it tells me that I should bring you in.”
Obi stared at her eyes. She had to lift her chin to look at him, and yet she was calm now, and not afraid. Her hand stopped shaking, as she pointed the gun at him
“Tell me something, officer Nako Kawakami. What is your duty?”
“To protect the law, of course.” Her father had taught her that justice demanded him to obey, serve and protect the law. He was her hero. 
Obi sighed. “Yes, of course. But let me try this again. What is your purpose on protecting the law to which you are sworn”
“To protect the peo--” she began, but stopped when she understood where he was leading her. “To protect the people, and to protect the animals.”
She lowered the gun, and he too lowered his arms. He walked to one of the chambers to the left, and entered through the glass door. Inside each chamber there were computers, microscopes, and a round table-shaped device with a multicoloured crystal ball in the center. Obi inserted the card in the computer, and typed at the keyboard with a speed that defied Nako’s belief.
“How do you have--”
“I made it,” he cut her short. Sometimes, rarely, he got the questions people were thinking right. “It wasn’t hard, if you want to know. I was actually surprised.” 
He was bypassing the security controls. The crystal ball began to glow, throwing up thick, almost solid beams of light. The beams started to move, touch, intertwine; multicoloured at first, then mostly white lines, bending and taking shape. Nako recognized it: it was the amorphous creature she had seen with her own eyes, but rounded and perfected. On the surface of the table that held the holocrystal, luminous letters displayed the code SZ-MKII MATRIX PROTOTYPE.
“This is the animal we tried to rescue, the synthozooid two matrix. You see, the synthozooid is designed to be a fully anesthetized organism: senseless, unaware. But this means that it is unable to think or act, because it receives such a small amount of stimuli, and has no recognition of its surroundings. It lives in a constant state of suspension of consciousness. It is always a prisoner, never free. 
“Still, there is a flaw in the zynthozooid’s design, one they cannot solve. Because it is blind to the its surroundings, weak and vulnerable, the mildest stimuli can trigger a panic attack. If the stimulus is strong--” Obi pointed at the blood splatters on the white chambers--“its heart cannot stand the stress, the high pressure, and explodes.  
 “But one thing doesn’t make sense.” Nako asked. “Why are they spending all these resources to create a new kind of synthozooid, when the current technology already works?”
Obi was silent. The computer hummed like the currents in the depths of the unfathomable ocean. Nako imagined being lost at sea, alone, with no sight of land to the right or to the left. Tied to a pole, unable to move, for days without end. Growing in the dark, and never knowing what the light is, until suddenly, out of the nothingness, something claws at you. Unbearable panic.
Obi typed at the keyboard, and the sound of keys woke her up. She sighed, alleviated. Light beams shot from the holocrystal, indicating a change in the projection. The body expanded, and the light beams formed a skeletal structure. From the creature’s forehead sprung two light beams that spiraled and bent. Horns. The amorphous creature took the shape, colours, and even the movements of an adult goat.
“The objective of synthozooid bioengineering was never to develop a new being,” Obi explained. “Every synthozooid grown is a step in research development. You think they really want to live feeding on this tasteless, artificially-flavoured, drug-injected lab-grown creature? Not quite.”
Obi stopped, and pointed at the blood-stained chambers. The sight still horrified Nako, and awakened one more red nightmare.
“In each of those chambers lived and briefly died many attempts to synthesize natural animals from the artificial synthoozoid matrix.
Obi typed at the keyboard, and the goat holograph distorted, taking the shapes of a doe, a cow, a sow. Nako looked at the chambers, and in each she pictured the animals in white, furless skins, atrophied eyes, gushing blood from the blowing of their panic-stricken hearts. In each red stain she saw the suffering of one of the supposedly anesthetized beings; she saw cruelty that could not be hidden. And then, she understood: through synthozooid research, MOGLE wished to anesthetize the animals—not the artificial ones, but those from the natural world, liberated on the Day of Reckoning— and slaughter them. Through synthetic meat, humankind was already been trained for the habit.
“You see where this is going, right?” asked Obi.
“You said before that the synthozoid’s death was a massive blow to MOGLE; that they lost a lot of money,” Nako said. “That means the operation was halted because of the incident, right?”
“Yes. But that is nothing. Not unless we destroy the biodesign specs, otherwise they can always create a new one.” Obi removed his card from the computer, and the holograph disappeared as the crystal sphere shut down. Nako followed him with her eyes, but not with the gun. He walked toward the mainframe, where he had been when she first entered the lab, turned it on, and began to type. The computer made strange noises and beeps, as if agonizing from an invasive surgery.
“If I let you do this, if I let you access this mainframe and erase the data, I will have helped to commit a crime. I will have committed a crime myself.”
As Nako said those words, a siren wailed outside the lab, accompanied by the sounds of car wheels, doors, footsteps.
“True.” Obi said. “So, choose what’s most important to you. But make it quick.”

* VI

The sign above her head read “10:37 GENÈVE”. She had heard that the clockwork precision of the Swiss train schedules was still a thing of wonder to people from other parts of the world. Yet, her whole life, that was just how the world worked: all parts working properly, according to their station and function; a system in perfect harmony. This mindset was what made her feel that she belonged here, despite her appearance, and the name everyone had difficulty at pronouncing. However, now she looked at the crowd rushing to and fro, with all their different faces, and felt like a stranger; not to this country, but to this world.
“You came,” said Obi, with a friendly laugh. “Are you here to arrest me? Should have told me before I bought the ticket.”
“No,” she said, with downcast eyes and no laugh. “And I couldn’t, even if I wanted to.”
“I know. I am sorry about that. It is my fault.”
It was, actually. But she didn’t begrudge him: most of all, it was her own choice. They walked together in silence, towards the platform. He carried a large backpack, and nothing more, and she wondered how it could be that he could fit all his belongings, all his life, in such a tiny compartment. “Where are you headed now?” Nako asked.
“Lyon,” he said, scratching his corn-coloured hair. “There are friends there, and adventures. You should come, too. Practice your French.”
“Shut up!” She said. “What are you talking about. Je parle français beaucoup mieux que toi, suédois idiot.” She reached into her handbag and produced a small brown paper bag. 
He opened it, revealing a keychain with a white mountain goat miniature. He gave a beautiful, sincere smile. “Omiyage,” he said; and she blushed, surprised. “Thank you very much,” he said, as the train arrived at the train station at 10:37.
That night, Nako got home and collapse onto her bed. Tomorrow, she would deal with her father’s thoughts, and her own plans for the future. But now, what she needed most was sleep, and it came quickly. She felt she was led to the boundless sea, floating towards unknown shores, and she looked up at sky. For the first time in many days, her mind was coloured by the lightest, brightest blue.

THE END
