#+TITLE: The wild boar of Corbenic:
#+SUBTITLE: An adventure in the times of King Arthur
#+AUTHOR: P. Schreiber

* I 
So it came to pass that in the land of the Fisher King by the Northern Sea, a terrible beast was wreaking havoc among the country folk. Farmsteads had been destroyed, merchants attacked and put to run for their lives, and even the people guarded inside the walls of the castle of Corbenic began to feel threatened, as reports reached them of a wild boar so huge that its tusks could lift boulders and rip apart trees.
Therefore, to bring back peace to his realm, a price in silver was offered by the king to he who brought the boar's head to the castle. What few possessions the peasantry of the land had were being ravaged by this menace, and some folks took up the courage to stand against it--peasants emboldened by the desire to save their lands, thugs and hoodlums from neighbouring countries, greedy for the shining prize. But soon enough there was no man left in those lands who would risk his life on such a mad quest; for those that did claimed nothing, but were claimed. 
Weeks passed, the terror remained, and the good people began to leave the land, lest their lives be taken. Seeing his realm at risk of being emptied of people and the few riches it had, either by death or by flight, the king decided to confront the menace directly. He ordered his host of archers be sent to slay the beast. The day before the task, boar meat was roasted, sending grey fumes to be carried by the wind towards the woods, provoking its dweller. A great feast was held at the castle in honour of the king's archers; everyone in the court was invited, and even some country folk that wandered about, banished from their farmsteads, were brought in to dine and be merry again, for their lands were about to be reclaimed.
When the golden rays of the sun touched the fields down the castle, the proud archers rode out of the gate towards the woods. There were garlands on their bows, cast upon them by the pretty maidens who cried their names with voices joyous and sweet, and some had on their faces the smiles of those who spend the night in good company. Proud and confident they were, renowned in this country and beyond as skilled and valiant, though their numbers were not great.
After some leagues of travel, the riders reached the forest whence the beast reportedly came from, where it should dwell when not causing devastation. On the outskirts of the woods there was a lumber camp, but not one soul could be seen or heard. The wooden walls were darkened and covered in moss, and some tools were left outside to rust, exposed to the rain. Whoever had worked there would come back no longer. Within the forest, the birds did not sing, as if fear of the evil that lurked in the shadows had silenced them; and the only thing one could hear was the crackling sounds of the cicadas. As they contemplated that lonely, murky place, the smiles faded from the faces of the noble archers. The commander rallied the host, ordering the horses be bound at the lumber camp.
"Let us reclaim our people's lands and rip off the fangs of this hellspawn creature," cried the commander, and the archers set their bowstrings with renewed courage.
"Now, we hunt.”
But the archers were not really hunters; they were men of war, used to fighting and firing on open fields and even terrain, not in the narrow, crammed spaces of the woods. When they were deep in the woods, where the leafy canopy was so thick that the sunlight barely entered, they were surprised, attacked from the back by a frantic charge. The wild boar's massive body trampled three or four archers on a single dash. The archers in disarray could not see anything but brown blurs and red stains.  
On that day, the king suffered heavy losses. 
News of the failure of the assault soon reached the castle of Corbenic, and the few survivors, gravely wounded, were sent to hospital ward. Within his hall, sitting on his throne, the Fisher King sunk his head on his hands, losing hope to overcome this great peril alone. He thought of his people's suffering; how he, their lord and keeper, could not defend them, and grieved. Three days passed; some men were healed, while others died from their wounds. On the fourth, the king summoned his courier.
"Send word to Camelot. Tell King Arthur we are in need of his aid.”

* II

After a couple days' journey, the courier could see the hills upon which stood high and proud the castle of Camelot, shining white in the bright sunlight. The horse halted for a moment, and the rider, though he had seen the stony towers several times, breathed deeply, filling his heart with hope. Arriving at the great gate, he saw hoisted colourful pennants and banners, fluttering in the wind; standards of great lords and knights from all across the realm, and he knew they would be assembled at the Round Table. Fortune was on his side. Wise and merciful, it was a custom of King Arthur to hear the pleas of his subjects in such occasions, before discussing matters of state. Thus, the courier from Corbenic was taken inside the King's hall to deliver his appeal. It was the first time he would speak to King Arthur directly; he was dazed by his magnificence, as if the gleam of his gold-embroidered mantle blinded him.
"I bring news from castle Corbenic, in the name of my lord King Pelles," said the courier, kneeling low before the King, touching the floor with his forehead.
"Please," said the King, signaling with his left hand. "Rise. King Pelles is a dear friend, and I would have his messenger be treated well. Now, tell us what brings you here.”
The courier rose.
"The eastern countryside is in grave peril, my lord. The farms and villages have been ravaged. A giant boar, they say, in a frenzy. The land suffers, the people flee in terror, and it shall not be long until it reaches the castle gates, where none can defend it.”
Whispers were heard throughout the hall. All the knights heard the messenger, as did some castle servants. The faint sob of a servant woman was heard; her family had remained in the eastern lands when she moved to the court, and she worried ever since. The King held out his hand, and there was silence.
"Tell me, how can one wild beast take out an entire village, let alone several? Have your people no hoes and shovels to till the land, axes to cut wood or bows to hunt, that they can use to bring it down?"
"It is no mere beast, my lord, but a fiend, hellspawn!", said the courier, and trembled.
The mumbling began once more around the table, somewhat louder. 
"Why did King Pelles not send his men to fight such a terrible threat, then?” asked the King.
"He did, my lord. Our forces were all but annihilated. Few came back, and fewer still recovered from their wounds. I beg you, our king begs you, o most honourable and merciful of kings, to save our people! Send your knights to stop this menace, before it destroys our country and spreads to other parts of the realm.”
Two knights raised promptly from their seats, none other than Sir Gawain, Arthur's cousin and most trustworthy of his companions, and Sir Lancelot, who already at his time was deemed incomparable except to the heroes of mythical times.
Sir Gawain had a lion's heart, and he worried about one he cared for deeply. For King Pelles had a daughter by the name of Elaine, who, like the princess of legend who shared her name, was a beautiful young lady; fair-skinned, with long golden locks of hair. It had been only once or twice that Gawain had seen Elaine, but that was enough for him to swear her love everlasting. She was the first thing that came to his mind when the Fisher King's courier was announced, and his heart was heavy with concern for her well-being. With his two paws upon the Table, he was the first the ask permission to take on this quest.
Now Sir Lancelot had a less stalwart look on his face, but he had his own reasons for wanting to leave the court of Camelot, especially in these times of peace, and go back to seeking adventures. His heart was troubled with love ill-suited, sinful, yet incurable. This affair, however, has been told of many times, and it would not avail to repeat it on this occasion.
The courier’s eyes filled with tears when he saw the two knights rising to answer his call. Not more than a country lad he was; he had only heard tales of the adventures of those men: how King Arthur had united the men of Britain and triumphed over the Saxon invaders; how peace with the Northmen had been achieved; how villages like his own were saved by the knights’ intervention; and of many a marvelous deed.
“Very well,” said the King, after consideration. “You shall ride at dawn, after mass, accompanied by two squires.”
The courier burst into tears of joy, and was taken by a page boy to feast among the castle folk. His appeal had been head and answered, but still other people awaited an audition with the King.
Meanwhile, away from the Round Table, the story was heard by Lady Morgana, Arthur's sister, who would later be called Le Fay, and who was at the time staying peacefully at the court. Though the other court ladies thought it unbefitting for a woman to dwell on the affairs of state, Morgana listened with utmost attention. She too was immediately decided to take on this quest. Not only would she be able to spend some time close to Lancelot, or so she thought, but mostly she was intrigued by the strange tale, and wondered what kind of marvel that was, that a single beast could thrash an entire party of archers and spread terror throughout the land.
After the audience, she approached her cousin Gawain, and it took only a gentle request for her to be taken along on the quest, much to the displeasure of Lancelot.
"It would not only be kind but wise to take me along, cousin,” said Morgana with a smile. "For as you know, I am skilled in the healing arts, and that may prove much more useful in this quest than this chanting of priests, as you may find out.”
Gawain smiled and agreed with pleasure. He was fond of Morgana, and never gave heed to the ill rumours about her that ran in the court. Furthermore, he was not a man of religion; his faith was all to the land and its King.
In the morning, the King wished them Godspeed, and the six rode down to the castle of Corbenic, in the realm of the Fisher King, upon the eastern coast far from Camelot. The courier and the two squires rattled with excitement of setting out on a real quest; but deep in their hearts, they felt terrified of what they heard about the boar monster.

* III

It was noon when the sentinel sounded the horn to signal the arrival of the party to the castle, after a two-day journey. The castle folk who knew of the courier's task and departure to Camelot cried with joy when they saw the great knights entering through the castle gates; children ran towards them to play with the horses, while women hug their husbands, and minstrels came to play them songs and sing their praises.
"The High King's faithful knight, his name is Sir Gawain./ By might of his long spear, our prayers shan't be in vain."
"Rejoice, fellow countrymen, grieve not for your lot./ Hope is restored o' this day, here comes Sir Lancelot!”
The fortress was crowded with people who had come from the fields seeking shelter, some of them well-born and well-dressed, the first to dig up their silver and run to safety; others with nothing more than their dirty clothes. How would all those people be fed, that was the question that came to mind. What good is silver when even bread would be lacking? The party made their greetings with smiling faces, and shook the people’s hands as a gesture of good faith. Hope, as the minstrel sang, was what they needed the most.
At his hall, the king stood up with his arms open and a smile on his face. Though he had a good friendship with King Arthur, he had not thought himself held in such high regard as to be sent the two best knights in the realm of Britain. Though his eyes had darkened in those tiring days, there was excitement in his voice when he addressed the party. They knelt before the king, as was appropriate, but he raised them and kissed their faces. Then, he took Lady Morgana by the hand, with the graciousness of a long-lived courtier.
"My lady," he said. "Your presence is like the first breath of spring on this wintry court. I hope our humble abode will suit you comfortably. May I entrust you with the care of my daughter Elaine, who is young and does not yet know much of the world?”
Now King Pelles was a devout Christian and had a distaste for what was said about Morgana--that she was a heathen, a sorceress, and worse. But she was nonetheless the lady of Cornwall and sister to the King of Britain, and a proud nobleman such as he could not hold those things in disregard. Furthermore, he wished his daughter be sent to the court of Camelot, to serve Queen Gwinevere as a lady-in-waiting, and this was a great opportunity to present her to one who could make that possible.
Later on, the knights and squires were taken around the castle and shown the armory, where they met the archers and men-at-arms that remained. The highest-ranking official was an old man who had fought alongside Uther Pendragon against the Saxons long ago, but who could now barely lift a spear, let alone wage war; the rest, though they seemed strong and capable, were crestfallen after the loss of their captain in the first hunt.
On the day before the arrival, another hunt had been called for by the king. Even some farmers who took refuge in the castle volunteered for the job, and the mission was led by one of the archers that had survived. But before they even found the beast, they heard growls coming from the woods, and turned back, fearing slaughter. Now, the sight of the knights of Camelot brought smiles to their faces, and raised their courage. One archer, who was the new captain of the guard, bowed his head and addressed them in salute.
"Sir Gawain of Orkney and Sir Lancelot of the Lake, it is the greatest honour to be given your aid," he said. "I am afraid we have suffered another defeat yesterday, but the men stand ready at will.” 
And they gave a great rallying cry.
"We shall discuss the preparations at dinner," said Sir Gawain. "For I have a request for your king. Now, if you may summon the blacksmith, I need my spear sharpened.”
Meanwhile, Lady Morgana was taken to her chambers--a large room with a clear mirror and a bed covered in linen sheets. She took off her boots covered in mud, put on light sandals and switched her riding breeches for a blue woolen dress with black details in silk, most elegant and suitable to the richest of courts. After washing her face, she went outside, and a servant took her to meet the young princess of Corbenic. 
Elaine was to be found at the courtyard, watering a colourful bed of flowers. Her locks of hair were yellow and bright like the daffodils; to Morgana, she looked just like the queen herself, only she was fair and virginal, while Gwinevere was regal, in full bloom of womanhood. She was startled like a wild doe when she heard the stranger's voice addressing her.
"I reckon you must be the princess Elaine," said Morgana. "There can be no mistake, for you are the queen's cousin, and I have seen her face many times.”
"Oh, I would not presume to claim any connections to the Queen of Britain," said Elaine, blushing. "I do not know that I have ever met the queen, to speak the truth.”
"You share her blood nonetheless," said Morgana, with a voice that was like gust on the fallen autumn leaves. "I know your father was not born in these lands, but came hither from Wales. You are a daughter of Arianrhod, just like Gwinevere, and the blood of the Celtic tribes of yore runs through you. That is a heritage greater than any riches in this world, and you should cherish it, child.”
“Oh, what is this you speak of?” replied the princess, and crossed herself. “I know nothing of the name you utter, but I know this: my mother was no heathen woman. This land was given to my father by the Pendragon after the war, and this is a Christian house.”
“Then, that is another thing you share with the queen,” said Morgana with a giggle of amusement. “But I do not mean to be impolite. I have not introduced myself. I am Morgana of Cornwall, sister to King Arthur. Your father has kindly asked me to take care of you while I stay in this castle, and I do not think it could be for a reason other than--"
“My lady Elaine!” interrupted a loud voice, joyful like a man who greets the noontide sun. “When news came of peril in this land, I came at once. Oh, that I would have come to you sooner.” 
Elaine shied away from the man, covering herself with a veil. He approached slowly and respectfully, and she looked at him and saw that he was a good man, whom she could not quite remember.
“Do not break my heart saying you forget, o fair lady of Corbenic.
‘Not far to the east, by the sea they say she lives
Maid of golden hair, made of skin so fair, Elaine.
And one man’s heart no other treasure can perceive
Than in his ear to hear her sing, wisp'ring his name.
To the maid of Corbenic he yearns his heart to give:
Knight and heir of Camelot, faithful Sir Gawain.’”
He bowed low to the young lady. When he lifted his head to look, her face was red like a strawberry.
“Oh, I am sorry, my lord,” said Elaine, with a charming obeisance. “It has been so long that I think I was no more than child when last I saw you. Is it true what they say, that you are come to kill the wild boar that ravages this land?
Gawain stuffed his chest and opened a broad smile.
“It is true, my lady. All will be arranged in the evening, and I ask you not to worry. I trust I will have the delight of seeing you at the feast tonight?” 
“Of course. And tomorrow I shall pray for your success. Now, if you excuse me, I must go back to my chamber. Will you please do my hair, my lady Morgana?
The ladies took their leave, and Gawain stood there smiling, with hands on his waist, happy as one who has reached the doors of paradise.

* IV

That night, though the country had been almost depleted of its riches, the king ordered a feast to be held, and there was food, wine, songs and merrymaking. When the knights appeared, the whole crowd exploded with cheers and applause. Gawain wore a blue jacket with a crowned lion on the chest, an emblem of his service to the King, while Lancelot wore scarlet, for even in hard times he could not restrain his taste for gallantry. The maidens sighed and swooned as they passed, and the men raised their mugs of ale. Princess Elaine, who was sitting between her father and Morgana, gasped and rose up to hide from sight behind the throne. Her eyes glittered as she stared at one of the gentlemen: an unexpected presence, who brought back memories of childhood, of a time when she was sad, having just lost her mother, and was comforted by a gallant knight’s kindness. She lost her breath, her heart pounded, her face warmed. She put her hands on her breast and smiled, having found a treasure she had almost forgotten.
The king rose with his arms open, and there was silence.
"Milords of Camelot," he said with a stout voice. "We are honoured by your presence. Here’s to the success of the quest, the fall of the wretched beast, and peace in this land!”
The crowd shouted hooray, and the bards resumed their playing. Trays were carried by the castle servants, and food was served. But before the king could join the feast, he saw that Sir Gawain still stood up. Their eyes met; Gawain, with a serious face, took a deep breath. The music stopped.
“My lord, I must ask you hear my plea,” said the good knight.
The king was surprised, for he thought himself supposed to be the one in troubled state. 
“You have my attention,” said the King. “And that of my court. Let us have it.”
“From the first step I took into your court, my lord, my heart sought but one, and when I gazed upon her, it was filled with boundless joy; the joy of the weary warrior who finds himself at home. Hither I came to ensure the safety of she who is dear to me; but that is no longer enough, and I don’t know if I can go back alone. Tomorrow, my lord, I shall go into the woods by myself, and with my spear bring down the mighty beast. And then I shall ask you, if I be successful, that you grant me this wish: that the princess be my bride, and that she join me at the court of Camelot."
The princess gasped, hiding behind the throne, but was unheard, for the hall was filled with the sound of gossip and surprise. The king scratched his thick beard, was silent for a while; then burst into laughter.
"This is a great gift," he said with a loud voice, so that the whole crowd could hear. "Not only you come to deliver my lands from harm, but you give it promise of a bright future! I tell you, Sir Gawain, that if you accomplish this task, you shall have not only my daughter, but lordship over this castle, after my passing. I am old now, far from my days of battle and love-seeking, and have no sons to whom I will pass on my crown; but you are an honourable man, and you can give me a grandson, a strong, handsome prince."
The king went forward and embraced the valiant knight.
"Bring me the giant boar's head, and my most precious treasure will be your prize."
Mugs were raised for the third time, and the bards resumed their merry songs once more. Gawain sat down alongside Lancelot to eat and drink, and Morgana came to kiss his cousin's forehead and wish him Godspeed. Then, in silence, she went towards the king's throne and fetched the hiding princess, unnoticed. Her eyes were swollen, her face was red, but it was not the same red as earlier in the afternoon. She rose up, holding Morgana's hand, and they went towards the dinner table. Gawain immediately noticed, for it was as if the hall was suddenly bathed in sunlight. He rose from his seat and stared at her with yearning eyes, but the princess did not meet them. The whole evening she kept her face down, and Gawain wondered whether she had heard anything.
After the dinner was over, Gawain rose from his seat and went to where the ladies were sitting. Elaine blushed, trembled, and almost hid her face, but the knight only took his cousin Morgana's hand and asked with a soft voice:
"My lady, would you play us a Northern ballad?"
She smiled, letting Gawain take her by the hand, and sat to play. She was not accustomed to the small harp, so she plucked the strings for a couple of minutes to get used to it. The whole place was silent, enraptured by her grace. Suddenly, seemingly random notes turned into song, the thin strings sounding like the tinkling of crystals. She was humming, and quiet though she was, her ethereal voice was heard all across the stony hall. The wind outside was the only other thing that could be heard, and the crowd shivered, pulling their coats tighter, as if winter breached through the cracks. But then a chant was heard, a man’s voice, charming and soft; and everyone was surprised when they realized it was Gawain’s, for he was a tall and stout man. He sang about one born in a snowy land, who was in love with the golden rays of the sun. The ballad was unfamiliar even to the bards, for it came from the Northlands. By the middle of the song, everyone realized who had composed the poem, and praises were sung for many years of the minstrel knight of Camelot.
When the song ended, it was like the cold had been banished from the land by the summertide. But though Gawain’s eyes searched the hall for his most beloved Elaine, the princess was nowhere to be found.

* V

The servant’s quarters were filled with the stench of bad breath and a symphony of snores. Sunlight entered through the window and revealed the two squires, sleeping on a bed that hardly fit one man, and the courier sleeping with his back against the stone wall. From the door came a commanding voice.
"Wake up, men", it said, and it was the voice of Sir Gawain. “Pastime is over, and now is the hour of duty.
The courier heard nothing, and his head fell on the floor to sleep over his hands, but the two squires jumped from the bed, startled, greeting good morning. They looked out the window and saw that the sun was high already; it was past the morning mass, so they patted their faces, strapped on their boots and made ready for their orders.
“I remember hearing my lord Gawain say he will depart alone for the quest,” said Sir Lancelot’s squire, whose name was Olwin. “Is that true? If so, I would not presume to advise you, sire, but with my lord Sir Lancelot’s permission I would offer you my service in all I can.”
The boy lowered his head, and Sir Gawain raised it with his large hand.
“It is true. Hear, I go not because of vanity, but because I must. Your offer honours you, lad; in recognition, I ask of you the simple task that would be my squire’s: go to the blacksmith and fetch me my spear, then bring it to the stable, where I will be. 
The two young men left, and Sir Gawain went to call upon the one he had to see before leaving. He passed by the courtyard where, the day before, he had seen her bathed in sunlight, beautiful, and his heart was filled with confidence and joy. One of the handmaidens was there, and he called her and asked to speak to her lady. The maiden was hesitant, for it was most improper that a high-standing lady be seen alone with a man, but she was moved by the sincerity of his feelings, having heard his declaration the night before. She asked him to follow her, took him to the lady’s door and knocked two times.
“I knew you would come,” said Morgana as she opened the door. Her voice felt like a chill wind on his warm heart. “Unfortunately, she cannot see you. I have told her you would come, and she turned red. She says she doesn’t feel well, and must stay in bed.
“Do you mean red as in flustered, shy, or red like one distraught with fever?
“Who knows what goes on in a young girl’s heart,” she said, facing downwards. “Do not be discouraged. You have her father’s blessings, and a good heart.”
“It is not his good will that I seek.”
She kissed his brow, and he left.
The outer gates were open, and the squires had horse and arms ready. Upon his steed, Sir Gawain gazed at the window of the princess’s room, but no one was there; so, with a deep breath, he turned his face towards the outside and rode. The sun shone brightly overhead, a true summer’s day. Its warm light cast away the shadows in his heart and filled it with strong resolve. He rode across green fields and barren farmlands, and though the lands were emptied and not a single traveler could be seen, he could not feel that the sunlight was anything other than a sign of hope.
When he had ridden for about an hour, and was nearing the woods where the king’s archers had reported the attack they suffered, he stopped for some water and a bite, and looking back whence he came, he noticed a black dot appearing in the horizon. At first he could not recognize it, so he blinked and saw that it was coming fast, straight towards him. Had he caught the beast’s attention? If so, it was no time to stand idle. It was the perfect place, a level plain field with nothing on sight but the grass, the skies and his foe. He strung his bow and laid some arrows in the ground, in the manner of soldiers, with shafts upwards. But before he would shoot the first one, he realized that the figure was too tall for a boar, and too slim for a monster. When it approached, it became clear that it was not a wild beast, but a rider.
“Who comes there?” He shouted, laughing. “If that’s you, Lancelot, I will smack that horse so hard it will go back to the castle flying. Did you not hear me say--”
But it was not Lancelot. The black rider did not answer, but approached in silence. 
“My lady! You ride with such vigour that I mistook you for a fellow knight.” Clothed in black travelling clothes he recognized his cousin Morgana. “What do you do here? This is a dangerous place, and I am afraid to say your presence makes this quest no easier.”
“We shall see about that,” she answered with that quiet yet far-reaching voice, but then gave a smug smile. “I realized Lancelot that fool would never indulge me with permission to accompany him, so my only chance to see what this is all about was to go with you, cousin.”
“I cannot take you, my lady, it is too great a risk.”
“Listen, you may not know this, but I have lived surrounded by the woods and the beasts since I was a child, and I know them well. This quest poses greater danger to you than to me.” 
Just like when she first asked to come along on the quest, he did not dare to protest, but mounted on the horse and rode onwards, with the lady on his tail.

* VI

The sun was at its highest point when they reached where the meadow turns to forest. Here the woods were not dense, but there was some open space, and the ground was level, except where the roots sprung from beneath the earth. The tall trees cast shadows like black stripes upon the land, but overall it was all very clear. Onwards, though, the forest became thicker, and with no sign of the beast, Gawain feared they would have to advance thither. It would not be good; the terrain here was good for a shot or for a charge, but in the deep forest he would be subject to the same danger faced by the men who took this quest before him.
"You can do what the fearful could not," said Morgana. "Call it. Challenge it and make it come to you instead of falling into its lair."
Gawain gave her a doubtful glance. Anger the beast, was she mad? But then again, was the beast not furious always? Maybe what had caused the others failure he could use for victory. So he nodded, and on his horn he blew a call that shook the leaves and resounded throughout the forest. There was utter silence for a minute. Then, a flock of birds flew from their nests and branches, scattering in the blue sky. A violent breath blew in the distance, coming from the depths of the woods--not the wind. Gawain looked in its direction, and in a dark brush he saw appear two bright yellow eyes.
He took the bow and set an arrow on the string. The yellow eyes disappeared for a second, but with a roar that seemed to make the ground tremble the beast jumped from the shadows and charged. Gawain staggered; it was enormous, the size of a fat bull with tusks instead of horns, and swift. He realized his rider's bow would be as good as throwing pebbles, and had only time to throw it away, take the spear with his two hands and point it at the beast before it threw itself on him like an all-engulfing wave.
The stampede terrified the horse. Gawain lost balance; his spear was deflected by the boar's tusk, and he was hit head-on with full force. Launched, tossed like a haystack, he hit his back against a tree and crashed on the floor.
The beast shook its head and body, breathing heavily. Morgana looked at Gawain and saw the stout knight unconscious, with his head on the ground. The beast turned its head towards her, and her horse neighed nervously, taking steps back and forth against her will. She dismounted, and just as she did so the animal ran away to the outskirts of the woods. The wild boar turned its eyes to it, undecided whether to chase it or not, but then fixed them at Morgana. 
But the beast took a few steps back. Its eyes turned red, its blood boiled, and its fur spur up like a husk of thorns. Thick growls turned to shrieks, as if seeing her made it even more enraged. But though it stomped the ground, it could not charge at her. She just stood there, alone, frail, helpless; but her will was stronger. She advanced and looked down with defiant eyes at the beast, which lowered its head and walked back, away from her. She came closer, and its eyes grew, terrified, as she gazed at them. To her surprise, she saw there was something inside them: in the black depths of the beast's pupils, a small figure stood in a vast dark space. It was the figure of a man, naked and alone. He looked up at her, startled, and trembled. He was tiny, and she was gigantic, standing above the black void. He ran, fleeing from her gaze, and just as he did, the boar shook its head, squealed and bolted into the depths of the woods; and she wondered if its cry was of rage or of pain.
She turned her head to Gawain, his large body thrown to a tree, fainted on the ground. She ran towards him, knelt at his side and touched his face. Slowly he opened his eyes; when the blurred sight of her became clearer, he grew worried and tried to stand up, searching for the beast. A great pain stung his side like a spear penetrating his ribs, and he cursed his fate, unable to get up. Morgana gave him water, which he drank, grunting.
“Where is it?” He asked with a weak voice. “Where is the beast? You are safe, but how? Now I understand why they--”
“Do not speak now, my dear,” Morgana said. She took a few dry leaves from a pouch, crushed them and put on his mouth. “Chew this, and swallow. It will not heal you, but it will ease the pain so we can go back to the castle.”
“Did I fail, mother?” He asked, with eyes full of tears.
“Do not weep. You are a strong man, and I am by your side. The wounds will heal in a few days.
But his deepest wounds were not of the flesh.
“Though I did set out on this quest for love to find,/ naught but pain, sorrow and defeat I found as prize.” 

* VII

Rain poured down ceaselessly on the day that followed Sir Gawain’s misadventure. The drops hit the window, and beyond the blurry glass, a grey sky, with not a single ray of sunlight. He had been brought to the room he shared with Lancelot the night before, which was wider and more comfortable than the infirmary beds. Morgana stayed with him the whole time, except when he slept, to bring him medicine and comfort him with stories and songs he liked to hear. But now it was past noon; he was alone, lying in bed, quietly contemplating the rain.
The day before, he had set out under enthusiastic ovation. But when he crossed the gates again, under the orange clouds of dusk, he found nothing but sad, hopeless looks on the faces of the poor castle folk. No one raised their voices against him, for when their eyes met with his, they knew his sadness was great, and his shame was punishment enough. As he approached the great doors of the king's hall, he saw that there stood Lancelot, and Elaine beside him, her face buried in his chest, wiping tears on his linen shirt. Lancelot put his hands on her shoulders, lifted her head and turned her face to the returning riders. Gawain and Morgana rode the same horse; its pace was slow, and though she held her head high as always, the crestfallen knight could not, but only stared at the ground.
"Gawain! Dearest friend," said Lancelot, walking towards him. "What news, and why the sad look on the people's faces? I do not believe one such as you could have been defeated.”
Lancelot gave his hand to Morgana, and she dismounted gracefully, despite the dirty riding attire. Gawain too dismounted, and though he was numb to pain from the medicine he was given, he felt a bite in his side, and faltered. Lancelot quickly grabbed his arm and supported him on his own shoulders; but Gawain did not want to be carried, so he put his hand on Lancelot's chest and pushed him away.
"Though I have lost the battle, I will not be carried like a dying man," said Gawain. "I can stand on my own, and will not have what's left of my pride taken like spoils.
Lancelot was surprised, but understanding his friend’s heart, he lowered his head and distanced himself. Lady Elaine came forward, and bowed to him.
"Welcome back, my lord," said she.
Gawain didn’t look at her, but entered the castle in silence, and did not speak for the whole day. He just wished for the showers to wash away the sorrow and shame in his heart. As he entered the castle, Lancelot hit the wall with his clenched fist, angry at himself, that he had let his friend take this dangerous task alone. Had he been there, would the result be different? Would they be returning both victorious, the country safe, and his friend able to have his most desired prize of love? That was his wish, and he cursed fate that everything had gone wrong, and that he had let Gawain convince him of his plan.
Not once did Elaine visit Gawain to see how he was doing. In bed, all the time he kept looking at the door, waiting--for what? Nothing, he knew. Only Morgana would come and go to bring him water and food, to sing and play the harp. Rain poured on and on.
In the second day, late in the afternoon, there was a knock on the door. Gawain looked up to see who it was, for Morgana would always knock three times. It was Lancelot, who slowly pushed the door and entered. He was unaccompanied. Gawain’s brows lowered, his eyes contorted, his teeth shut, as he refused to look directly at his visitor. Lancelot took small steps towards him. He knew what his friend had seen, and had no need to ask why the long face and avoiding eyes. 
“Hero of Camelot,” taunted Gawain. “What brings you hither other than to disturb my rest and to mock my suffering? To boast, having won what means nothing to you, but that I would treasure as the most precious jewel in the whole world?”
“Mock?” asked Lancelot angrily. “Did that beast break not just your bones, but also your senses? That I would dare mock the man who, as a young knight, with a spear and no shield pierced twenty Saxons to protect his King; who tamed the feral Northmen to lead them into battle against the hordes of Hrothulf, the Bearskin; a battle in which the songs say the clash of steel sounded like thunder, and the two men looked like mountain giants; that I would lower myself to scorn such a man because of a young maid’s barley braids, it is a ludicrous idea.
“Damned be you, snaketongue!” said Gawain, and he clenched his fist and punched Lancelot in the chest, making him cough. “But you are right. Though they say the bonds that tie two lovers are strong, ours are stronger still, for they are made of iron, forged in the heat of battle.”
"That is the truth", said Lancelot. "And that is what brings me hither: our quest is unfinished.
"Yes. Alas, they say love is not something to be taken, but must be given, and now I see. Her heart was never mine, else I would have prevailed. Now, it is your turn to do what I could not.”

* VIII

A mighty horn sounded across the clear skies that covered the Fisher King's lands, its echoes reaching far, beyond the Northern Sea coast, the sunlit hills, meadows and the woods. It was the uncanny sound of the horn of Sir Gawain, who stood on top of the highest tower in the fortress of Corbenic. Two times it blew, inspiring awe in all men and women, who looked out their windows to see whence came the heroic call. On the second, the chains of the castle gates rattled, and they opened. Then there was a fierce gallop, a white horse speeding inside the walls, its hooves raising a cloud of dust from the ground. A third time blew the thunderous horn, and like a scarlet lightning bolt rode Sir Lancelot, outwards into battle.
A hawk soared the skies after the valiant knight, and flew towards the southern woods. There, the leaves of the highest trees were shaking, and all the animals were stirred. A growl louder than ever before was heard even inside the castle walls, making women and children cry. With her hands upon the window frame, gold, radiant hair blowing in the wind, from her high chamber the fair Elaine looked outside the castle with keen eyes, staring at the scarlet rider, who quickly became a small dot in the distance. She threw her arms towards him, and her lips blew a kiss so filled with love and yearning that the wind rushed to carry it to him.
Among the clouds, above the depths of the forest, the hawk started to fly in circles. The creature was there below; it had heard the daring call, and approached at a fast pace, soon to reach the sparse woodlands. On the high ground of a hill, Lancelot alighted from the horse and made ready his defense. He did not advance, but waited on the clear grassland, steadfast. Far below, from among the woods he saw the wild boar appear, immense, growling; the sound it made shook the earth and the leaves, and instilled terror in the hearts of all men and women of the land. But the knight’s heart was not stirred; he expected nothing less from the beast that had caused such devastation. He held a bow in his hand; not one for hunting small game, but a powerful war bow, as tall as an adult man. With his eyes fixed on the foe, he reached for an arrow, set it to the string, and pulled it to his ear. He loosed his fingers, and with such force the arrow flew that it disappeared in the clear blue sky. Far ahead, the beast tripped and squealed, a shrill cry that would freeze one's soul. But Lancelot's heart was ablaze, and he did not falter: another arrow he shot, and a third one. Five times he hit the creature, each thick shaft penetrating its flesh with tremendous force.
The boar’s dark fur consumed the sunlight; spots of grey made it look like an iron husk, and the arrows springing outwards were the like the spears of a phalanx. With every rushing step, it seemed to grow larger; not a boar, bull or bear, but a true monster. Despite the damage, it would not go down. On a fast pace it crossed the woods, the meadows, and was coming up the hill. The stampede seemed unstoppable. However, this was not the irregular terrain of the woods, but a clear field--a field of battle. Lancelot threw the bow to the ground, and with two hands he held high a spear, and the spearhead was as long as a straight sword; for it was Gawain’s spear, gifted by King Arthur himself after the battle against the Saxons under Hrothulf, the Bearskin. And its name was Cruaidhchas, hardened shaft, for though Gawain’s strength had bent and broken many a spear, this one had never splintered once, and it was said to be unbreakable.
Lancelot pointed the spearhead at the charging beast, and it glinted in the sunlight. A bright flare hit the monster’ red eyes, and it shrieked and shook its head furiously. In the frenzy it jumped, throwing its enormous bulk at Lancelot to ram him with its hard tusks. With the full force of his back, Lancelot thrust the spear forward. Eyes burned by flare, the beast raised its head to avoid it, and the spear pierced its chest, blade and shaft straight into the heart. There was a spray of dark red blood, and the beast fell upon the grass. The climb upwards had cost a great toll on its heavy body, and it couldn’t keep up the charge.
Lancelot pulled the spear from the carcass; blood spilled and painted the grass black, as the boar convulsed one last time. He let himself fall, sitting on the ground, and rested. The strain was heavy on his arms and shoulders, and for almost an hour he barely moved, but just stayed there, looking at the clouds. Then he heard a screech; up in the sky the hawk was calling. Looking back towards the north, he saw three riders approaching, so he stood up proudly, holding the spear.
“My lord King Pelles,” he said, recognizing the three as the king, the new captain of the guards and Morgana. “It is done.”
The king sighed with relief, and threw his hands up to the sky. Lancelot went towards the beast. Looking at its face he saw that one of its large fangs was broken. He stretched his hand to the other one--he wanted to take it to make a present for the king--but was interrupted by Morgana.
“What are you doing, Lancelot?” She said. “If it is a trophy you want, you can have the other fang; I have it, and I am sure Gawain does not want any keepsake from this quest. Leave the poor creature be. He has paid for his wrongdoing, and should suffer no longer.”
He. Just when Lancelot stopped his hand, the carcass moved; the huge bulk of flesh shrank, and black fumes exhaled from the sides. It was as if all that was left was the creature’s furry skin, like a cover blanket. Despite what Morgana had said, Lancelot pulled it up: underneath, the body of a man, long-haired and handsome; dead, with a huge scar on his chest.

* IX

Years before, the story ran, there was among the country folk a peasant maiden, who was beautiful like a wild primrose. Her father was a man of esteem, the head of a village, with a large family and a good plot of land. His primrose he believed to deserve a great fate, and he betrothed her to a soldier who would take her to the court. But when a shepherd boy of the village learned of this, he went to her and declared his love. Though she had accepted the engagement, she was beguiled by the handsome shepherd, and together they fled the father’s house. But his heart was not true, and as he grew more handsome by the day, so did his love wean. The primrose, now a woman who had cast away her good family, a good marriage, a good life, all for the love of a wanton man, felt betrayed, abandoned. Such was her spite, that one night she stabbed him in the back and cursed him: if like a swine he acted, a swine he should be.
The man was buried outside the castle walls; though he had caused great harm, it would not do to leave him where he fell. None attended the funeral, and there was none to mourn him.
Two years later, in the coming of springtide, the princess Elaine of Corbenic, daughter of the Fisher King, was married to Sir Lancelot of the Lake. Gawain’s friendship to Lancelot remained strong, undamaged, until the day another affair would throw those two in bitter enmity.
