#+OPTIONS: toc:nil num:nil
#+LaTeX_CLASS: simple-resume-cv

* Pedro Schreiber
schreiber.mmb@gmail.com | +5511997612304

*Software engineer with 5 years of experience* developing different aspects of computer systems and web applications.

** experience
*** Stone - software engineer 2022 - current
Stone is a /fintech/ company that provides services such as POS terminals, online payments, and ecommerce
to small and medium-sized businesses. I worked in the /identity platform/ team,
designing and programming systems for notifications, registration, authentication and authorization,
in a complex architecture of multiple microservices. My work includes:

- *Integrations with external services* for sending email, sms, and push notifications;
- *REST APIs* to provide fetching and putting data on the databases, and publishing events;
- *Apache Kafka* producers and consumers for asynchronous processing of application events;  
- *Documentation* for systems, functionalities and code,
  in the form of module docs, api docs, and articles
- *Unit and integration tests* using programming language tools,
  test databases and sandbox environments.
  
*** Árvore - software engineer 2021 - 2022
Árvore is an /edtech/ company that provides a digital library for students and teachers as a subscription.
I worked in the /product marketing/ team, designing and programming features
for client acquisition in the product. My work includes:

- *MVC architecture* code in Elixir and Ruby on Rails; 
- *GraphQL APIs* to manipulate the database and integrate backend and frontend;
- *React.js* frontend, including global state store and GraphQL client;

*** BETC Havas - software engineer 2020 - 2021
BETC Havas is an international marketing agency which creates innovative marketing strategies.
I worked in the /web development/ team, coding the website for the telecom company TIM.
My work includes:

- *Vue components* for dynamically rendering data produced by the business team;
- *SASS/CSS stylesheets* for styling web pages; 
- *Static file database* using XML tables to store business data;   
- *Legacy systems* for deploying web pages through FTP and internet explorer Java applets.
  

*** Newbacon - CRM analyst 2018 - 2019
Newbacon is a data-driven marketing agency which provides business insights and communications.
I have work in the /CRM strategy/ team, creating communications flowcharts to drive customer engagement.
My work includes:

- *SQL database for business analytics*, retrieving and analysing customer cycle data;
- *Email and sms templates* rendering dynamic data retrieved from the database;


*** LQDI - Web Developer 2018 - 2019
LQDI is a marketing agency which creates design and technology solutions. My work includes:

- *HTML, CSS, Javascript* for creating web pages and email marketing;
- *Reactjs* for writing web apps.

*** Rudek Wydra - content writer and web developer 2016 - 2018
LQDI is a marketing agency which creates websites and email marketing for the manufacturing industry.
My work includes:

- *Wordpress* websites;


** education
- Universidade Anhembi Morumbi - BS, Computer Science (2020-2024)
- Universidade de São Paulo - BA, Philosophy (2010-2015)

** languages

- Portuguese :: native/proficient 
- English ::    fluent/proficient 
- French  ::    intermediate      
- Spanish ::    intermediate      

** tools

| *Languages*          | Elixir  | Go         | Python | Javascript   |
| *Frameworks*         | Phoenix | React      | Vue    |              |
| *Databases*          | MySQL   | PostgreSQL | Redis  |              |
| *Infrastucture, etc* | Docker  | Kubernetes | AWS    | Apache Kafka |


** courses and certifications

- Senac - Introduction to Computer Hardware and Technical Maintenance (2008)
- University of Cambridge - Cambridge English: Proficiency (C2)
