#+OPTIONS: toc:nil num:nil

* Pedro Schreiber
schreiber.mmb@gmail.com | +5511997612304

** SUMMARY
*Software engineer with 5 years of experience* developing different aspects of computer systems and web applications.

- Backend development with languages and frameworks like *Elixir/Phoenix, Javascript/Node, Python/Django/Flask*,
  providing *REST and GraphQL APIs* for web applications and services;
- Frontend development with the vanilla stack of *HTML, CSS and Javascript*, frameworks like *React, Vue, Bootstrap*,
  and tools such as *SASS and Typescript*;
- Distributed systems architecture and asynchronous jobs processing, with *Apache Kafka, Rabbit MQ, and AWS Lambda*;
- Database systems, such as *MySQL, PostgreSQL, Redis, MongoDB*, and caching with *Redis*.
- Cloud and infrastructure for deploying applications to AWS, using services like *EC2, ECS, Fargate, S3*,
  and tools like *Docker, Kubernetes and Terraform*;
- *Object-Oriented Programming*, with a solid *understanding of patterns* and languages like *Javascript, Python, Ruby*;
- *Functional programming languages*, with practical and theoretical understanding of concepts and languages
  like *Elixir, Erlang, Haskell, and Lisp*.

** EXPERIENCE

*** Stone - software engineer 2022 - current

Developed an application that delivers notifications (email, sms, push, webhooks) to millions of users
and applications daily, through *asynchronous processing of Kafka events*, with configurable
message templates and file attachments.

Developed account authentication and authorization systems, providing user registration
based on *UML data diagrams and REST APIs* to structure and manipulate the database,
and *OAuth 2.0 protocol-compliant tokens with cryptographic signature and encryption*.

STACK: *Elixir, PostgreSQL, AWS, Docker, Kubernetes, Apache Kafka, React*

*** Árvore - software engineer 2021 - 2022
Developed an application that provides a digital library for schools,
with an *MVC architecture* and complex modeling of user groups and levels, and *GraphQL and REST APIs*
to integrate the React web and mobile frontends with the MySQL database backend.

Led the technical support team, with the responsibility of investigating and fixing problems
with user accounts and system features, mostly by checking system logs
and correcting inconsistencies in the database.

STACK: *Elixir, Ruby on Rails, PHP, React, MySQL, PostgreSQL, AWS, Docker, Kubernetes*

*** HavasPlus - software engineer 2020 - 2021

Developed the website for the telecom company TIM, and modernized a legacy system
to allow dynamic data rendering, by implementing a database backend
and *Vue components written in Typescript*.

STACK: *Typescript, Vue, HTML, SASS, Node*

*** LQDI - Web Developer 2018 - 2019

Created landing pages and email marketing in pure HTML, CSS, Javascript,
and using tools like Vue components for interactivity and Bootstrap for responsiveness.

STACK: *HTML, CSS, Javascript, Vue*

*** Newbacon - CRM analyst 2018 - 2019

Created data-driven email and sms communications, using SQL database and
CRM tools to map client engagement with marketing campaigns.

STACK: *MySQL, HTML, CSS*

*** Rudek Wydra - content writer and web developer 2016 - 2018

Created institutional websites for manufacturing industry companies
and technology events, using Wordpress templates.

STACK: *HTML, Wordpress*

** EDUCATION
- Universidade Anhembi Morumbi - BS, Computer Science (2020-2024)
- Universidade de São Paulo - BA, Philosophy (2010-2015)

** LANGUAGES

- *Portuguese* native/proficient
- *English* fluent/proficient
- *French* intermediate
- *Spanish* intermediate

** COURSES AND CERTIFICATIONS

- Senac - Introduction to Computer Hardware and Technical Maintenance (2008)
- University of Cambridge - Cambridge English: Proficiency (C2)
