 #+TITLE: Chant for Leto
#+AUTHOR: P.Schreiber

* Lycia

Lycia, Sarpedon's most splendid seat 
Thy seaborn sons are strong from Helios's heat,
Their beards are bold, and brine incrusts their curls;
Thy daughters' presents, eyes that shine like pearls,
Fair faces framed by strands of black moonlight 
That flow like Xanthos' water in the night.

The temple lined by limestone colonnades;
Ahead, three statues stood: The twins displayed:
Apollo, bearer of the Silver Bow,
Artémis, huntress maid'n under the boughs,
Leto, the lady of this lavish land,
Whose majesty my mind's eyes did command

Atop the tall hill, on the higher grounds
That overlooked the lower neighbouring towns,
Stood stones of an old castle, ruins almost
Forsaken not by people, but the worst,
'Twas rather spirit that was scarce inside
And in the haunted halls would not abide

The windows, walls were scarred by want of meeds,
And grass was overgrown with wasted weeds;
A servant of the estate had seen it all,
Forsooth, for fourty years, through rise and fall,
And laid on me the lore: the lord survived,
Though Death, alas, did take his dearest wife.

* Summoning of the Muse

I summon thee to sing, oh Sorrow, muse
Of lovelorn souls, who're lost, by Love refused;
Impart on me the art to tell the tale
Of love unlike the ones this life's entailed.
Poor poet, I, of persuasions proud,
But now all my beliefs obliged to doubt.

I've oft inquired after my faults and errors
If's right to raise a shield 'gainst Eros's arrows.
But healthier to open up the heart
Though passions may evanesce, two shared souls part,
And Acheron o'erflow with salty streams of tears
The harm may heal through many months and years.

O while it lasts how marvelous' the delight
That I would take a thousand tearful nights
For a single day of dalliance with my adored,
One tender stare full of intense ardour.
Even of misery it's worth every measure
If just to unearth such rare precious treasure.

Yet other men might meet not mirth, but gloom
When their lives mark the anathema and doom
Of thy majestic mother Mnemosyne
When the cruel Fates cut lines ere intertwined.
Oh wicked man who loveless mires must wade,
And pours libation blended with nightshade.

* The Abduction of Persephone

They built a castle in the city, a crystal palace where dreams came true.
It turned happiness, an idea, into a manifest reality
And eternity, a universal concept, was boxed into a small plot of land
And locked inside stone walls
Causing imbalance in the cosmos

Like Zeus punished Prometheus for stealing the fire,
Like Persephone's abductor, fancied you, taking your for the image of his dark mother.

To make ideas to mundane matter bend 
Is a prerrogative of gods, not men;
So Dream, who by this deed took dire offence,
Did for the crime cast cruel and swift sentence;
Yet, craven he was, and called his brother Death
To join togeth'r to take this terrible act.

The black-night brothers on the couple spied,
And Hypnos, his heart filled with heaps of spite,
Put her to sleep between here and beyond.
Then Tanathos, 'gainst Hera's godly bond,
The fair-faced femme did fancy, and at night
Abducted her to Hades as his bride.

Now the castle is a ruin
They crystals foggy and in shards
The gods win, as always
And the loser is man
She is Death's bride now
And he is alone
The sun and daughter, cursed, motherless
And no lesson is to be learned.

* Dirge

The lord of the house poured wine in his guests' cups and sang:

Every fracture in these walls is a sign of the splitting fibers in my heart,
Wailing, weakened, wounded by your loss;
And just as these split strings have never healed,
I never found the strength to repair our walls, the holes in the carpeted floors.

The flowers in our garden waited so long for your return,
And still, even if there is now nothing but wasted weeds,
Underneath the earth I believe they sleep,
The rose, the gardenia, the lily and the violet.

hers
hearse

I never smelled the rose again;
It is your ghost, the cloud of scent of your perfume
The venomous aldehidic poison and the mystic patchouli, mixed with the smoke of cigarretes
You, my sorceress, my fairy, my queen.

* The Paintings

In a drawer of an old chiffonier I keep the album with the fotographs of our wedding
In fourty years, despite the tint of sepia, the colours are still vivid
They remain, the images and memories of your raven hair, your beautiful smile
as if a lovely spell kept them from oblivion, thought death took you

Oh, how I look in these fotographs like a child
A fool, a love fool,
The stupid smile of a man who can't believe his luck
Who now looks in the mirror, and what do I see
Not a smile

