#+TITLE: Episódio 001: Within The Realm of the Dying Sun

* A ideia do podcast

A ideia do podcast é poder conversa gerar conversas sobre
discos, livros, filmes e outras coisas interessantes.

O objetivo egoísta do podcast é encontrar outras pessoas interessadas nos assuntos que
me interessam, e que são tão difíceis de encontrar. Se houver um garoto no interior do
Tocantins que ouve Dead Can Dance e não tem com quem compartilhar o assunto, esse é o
espaço para isso.

* Dead Can Dance

Dead Can Dance é uma dupla australiana que faz uma música difícil de descrever.
Gótico, místico, espiritual, world music, new age são algumas expressões que descrevem a dupla.

A dupla começou a carreira nos anos 80 em Londres, no mesmo lugar e tempo que outros grupos góticos
clássicos: Bauhaus, The Cure, Sisters of Mercy. 

Mas Dead Can Dance tem outra cara. Carrega influências de música turca e grega, ritmos africanos,
música celta, tudo isso em uma apresentação cinematográfica, gótica, dream pop.

*Brendan Perry* é o roqueiro da dupla, e por sua conta fica o lugar da dupla no cernário gótico
dos anos 80.

Tem uma voz única e difícil de descrever. É um pouco rouca, mas não é grave. Não é
linda e aveludada, mas tem uma certa imponência. 

*Lisa Gerard* é a musa cantora da dupla, e é quem impõe o caráter cinematográfico e sublime
ao som da dupla. Já participou de várias trilhas sonoras, inclusive a do filme Gladiador,
e inspirou diversas cantoras/imitadoras.

Quando eu morrer, eu quero estar ouvindo o disco solo da Lisa Gerrard, "The Mirror Pool".
É a música que eu quero que me transporte para o outro mundo.

O documentário sobre a Lisa Gerrard conta que na infância ela fez aulas de canto lírico,
mas ua vocação estava em um canto mais intuitivo, livre, criativo, e na linguagem inventada.

* Within the Realm of the Dying Sun

Within the Realm of the Dying Sun é o terceiro disco do Dead Can Dance, e na minha opinião
a obra máxima. Para mim, nenhum outro disco tem tamanha capacidade de apagar as luzes,
cobrir o mundo de escuridão, e nas trevas elevar a alma, transportá-la para um mundo mais bonito,
eterno talvez.

Os primeiros discos eram composto como uma mistura intercalada de músicas dominadas
pelo espírito masculino ou feminino, Brendan ou Lisa. Neste, a divisão é radical. Das 8 músicas,
as 4 primeiras são de Brendan, as 4 últimas de Lisa. Espiritualmente falando, no caso.

O lado A tem influências do rock gótico dos primeiros discos, e é mais verbal -- característica
do Brendan Perry, contador de histórias.

** Anywhere Out of the World
A música de abertura tem o nome de um poema em prosa de Baudelaire.

A letra tem o mesmo sentimento do poema, de individualidade, melancolia, e a mistura de
desespero e esperança:

#+BEGIN_QUOTE
We scaled the face of reason
To find at least one sign
That could reveal the true dimensions
Of life lest we forget

And maybe it's easier to withdraw from life
With all of it's misery and wretched lies
Away from harm
#+END_QUOTE

O disco já começa de forma aterrorizante, com os sintetizadores que caracterizam o som do grupo
e as vozes de coral gravíssimas enchendo a sala com o wall of sound: PAAAAAM PAAAAM PAAAAM, e
o baixo sincopado com o sintetizador mexendo com as batidas do coração.

A música tem toda a cara de um rock gótico, só que transformado numa composição dos elementos
mais simples: baixo como peça rítmica harmônica, sintetizador como peça harmônica e melódica.

E o solo de teclado, que coisa bonita.

** Xavier

A música começa com uma parede de sons e o canto da Lisa Gerrard, começando a levar a obra
(o disco) para outro mundo. É como se fosse o ultimo momento de rock gótico do disco, da banda.
E que pedrada de rock. De novo, um rock transformado, mas uma pedrada. Não é à tôa que a música
foi tocada (cover) pela banda de doom metal Paradise Lost. Ouvindo, dá perfeitamente para imaginar
os sintetizadores como guitarras com alta distorção e reverb.

E que momento de potência vocal quando o Brendan Perry canta /"And as the night turns into day"/!
Lindo demais.

#+BEGIN_QUOTE
And as the night turns into day
Will the sun illuminate your way
Or will your nightmares come home to stay?
Xavier's love lies in chains
#+END_QUOTE

Essa estrofe sintetiza tão bem o disco, para mim. É um som das profundezas e da escuridão,
mas que olha para cima, esperando a luz, a alegria. Essa música é uma obra prima.

** Dawn of the Iconoclast

Virar o disco para o lado B é como dar um mergulho nas profundezas. Não tem mais roquinho
para confortar o ouvinte. Agora é pura treva. A música é um convite para essa jornada.

Detalhe da performance da Lisa Gerrard, o "ah ah ah" com um efeito maravilhoso.

** Cantara

Olha, eu não vou nem comentar essa música, porque eu não tenho palavras que consigam começar
a descrever essa *pedrada* de granito no ouvido.

É uma jornada. Me traz à cabeça a imagem da Maria Callas como Medeia no filme do Pasolini:
uma rainha feiticeira grega, viajando sobre as águas, pelos desertos, pelas cidades antigas.

A influência grega da Lisa Gerrard é muito forte nesse disco, mas ela não parece real,
é mitológica e cinematográfica.

** Persephone

Persephone é também uma pequena síntese do disco (do mesmo jeito que o verso que eu citei de
Xavier). A música começa nas profundezas das trevas, e faz uma elevação em direção à luz.
É realmente como Perséfone, no Hades, subindo uma escada para rever a mãe Demeter, e
voltar à vida. As teclas do teclado são como degraus de uma escada de cristal.

* Influências, etc

A linguagem inventada (glossolalia) das músicas da Lisa Gerrard é uma óbvia influência
do Neige, da banda Alcest, que tem várias músicas assim (Delivrance, Kodama, Sapphire, etc).

Em um vídeo da loga de discos [????], o Neige escolhe Within the Realm of the Dying Sun como
um dos seus favoritos. Fiquei tão feliz, eu sabia que eu tinha uma conexão com esse cara.

Nesse disco, a performance da Lisa Gerrard tem um quê de bruxeza de uma Diamanda Galás,
mas mais elegante e não hostil como ela. É como se as duas cantoras fossem duas faces diferentes
da deus Hekate, uma mais violenta, outra mais... 

Curiosidade. A capa deste disco é uma tumba no cemitério Père-Lachaise, em Paris. Esse ano
eu consegui realizar o sonho de visitá-la. Tive que andar por todo o cemitério, cansado, até achar.
Mas estou muito feliz de ter encontrado e tocado esse pedaço da história da música.

O disco tem 38 minutos. Se eu tivesse que escolher entre os 38 minutos deste disco ou
todo o resto da história da música do universo, escolheria esse disco. É um desses discos que
quando acabam eu não quero ouvir mais nada, porque não existe uma experiência à altura. Melhor
ficar uns minutos sob efeito da experiência que acabou de acontecer.
