#+TITLE: O filme que só você viu (working title)
#+AUTHOR: P. Schreiber

A ideia é gravar 10 episódios de podcast sobre assuntos que parece que só eu vi e gosto,
mas que quero encontrar outros malucos para conversar sobre.

Só vou lançar o podcast depois de gravar 10 episódios. Abaixo, os primeiros temas
(e possíveis convidados):

* Within the Realm of the Dying Sun

Discutir a banda Dead Can Dance e o disco Within the Realm of the Dying Sun.
Este episódio eu vou ter que fazer sozinho, porque não tem mais ninguém que
eu conheça que ouve isso. Depois que encontrar pode ser que dê pra fazer uma v2.

* Sleeping Beauty

Discutir o filme Sleeping Beauty.

* The Tale of Genji, pt.1

Discutir o livro Genji Monogatari

* Ecailles de Lune, c/ Bruno Ferraro

Discutir a banda Alcest e o disco Ecailles de Lune.

* World on a Wire, c/ Lucas Brito

Discutir o filme World on a Wire.

* Neuromancer, Idoru, Pattern Recognition, c/ Marcelo Muller

Discutir or livros Neuromancer, Idoru, Pattern Recognition.

* Relationship of Command + Doppelganger, Marcelo, Lucas, Bruno

Discutir os discos Relationship of Command e Doppelganger.

* Perfect Blue, c/ Marcelo, Lucas, Bruno, Enos

Discutir o filme Perfect Blue.

* The Tale of Genji, c/ outros

Discutir o filme The Tale of Genji e a trilha sonora feita por Haruomi Hosono

* Comida Indiana, c/ outros

Discutir a comida indiana e por que é a melhor do mundo.


* Bonus

** A Irmandade dos Pré-Rafaelitas
** JMW Turner
** Computação e Filosofia, c/ Aryel e Igor
** O Navio Fantasma, Wagner, c/ Bruno, Igor
** Blackwater Park
** King Crimson
** Diamanda Galas
** Whisky, c/ Aryel
** Silmarillion, c/ Isadora
** Townes Van Zandt, w/ Katherine
** Revolutionary Girl Utena
** Fate Zero, Puella Magi Madoka Magika
** ** Ruroni Kenshin: Tsuiokuhen
